### ISSUE TITLE
进入商店无法退出

### ISSUE THREAD

**Issue by lyk0712** [sMythicalBird/ZenlessZoneZero-Auto#102]
![Uploading 屏幕截图 2024-08-01 213407.png…]()

**Comment by sMythicalBird** [comment]
你这图也没上传成功啊

**Comment by ccc007ccc** [comment]
游戏分辨率不是1280x720会出现这种情况

**Comment by lazydog28** [comment]
> 游戏分辨率不是1280x720会出现这种情况

readme里说了，游戏分辨率必须设置成1280×720
