### ISSUE TITLE
壓力門

### ISSUE THREAD

**Issue by kindson07** [sMythicalBird/ZenlessZoneZero-Auto#103]
在壓力門不會選藍色事件 一直選白色事件退出 是要改參數？

**Comment by lazydog28** [comment]
[推荐游戏设置](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/wiki/%E6%8E%A8%E8%8D%90%E6%B8%B8%E6%88%8F%E8%AE%BE%E7%BD%AE)

如果已经设置了推荐游戏设置还是压力门的话，尝试调整屏幕缩放再试试

**Comment by kindson07** [comment]
调整屏幕缩放100%? 我平時125%

**Comment by sMythicalBird** [comment]
> 调整屏幕缩放100%? 我平時125% ![image](https://private-user-images.githubusercontent.com/109346442/354439111-61c14e8c-55ec-44b0-ba01-fd4ac4e488f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1ODA5MjAsIm5iZiI6MTcyMjU4MDYyMCwicGF0aCI6Ii8xMDkzNDY0NDIvMzU0NDM5MTExLTYxYzE0ZThjLTU1ZWMtNDRiMC1iYTAxLWZkNGFjNGU0ODhmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQwNjM3MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzE0YzI4OGJkZjMxYzJlNTQwYmJkNThmMTVmNmM3NDU3ZGVmZTVhMzVhY2QxZjIyOWYyMzU1NTk0Zjg5ZTVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PXKmLEmMMuCQ_brw3Mq3ZVtdbrVKJWF_9-KcEsOsEjo)

调成100，4k屏可以再试试其他比例，部分屏幕的缩放对ocr有影响，我们没那么多设备去挨个做适配

**Comment by sMythicalBird** [comment]
此外游戏语言选择简中
