### ISSUE TITLE
问题求解

### ISSUE THREAD

**Issue by EArenZ4** [sMythicalBird/ZenlessZoneZero-Auto#104]
ParserError: expected '<document start>', but found '<block sequence start>'
  in "C:\zzzauto\ZenlessZoneZero-Auto-master\tactics.yaml", line 3, column 1

**Comment by EArenZ4** [comment]
![Uploading ZZZ.png…]()

**Comment by lazydog28** [comment]
看报错信息应该是配置文件有问题

**Comment by sMythicalBird** [comment]
> ParserError: expected '', but found '' in "C:\zzzauto\ZenlessZoneZero-Auto-master\tactics.yaml", line 3, column 1

下次传图片，不然不知道你在说什么，不过看你应该是再说战斗策略的问题，tactics在2.1已经弃用了，换新代码
