### ISSUE TITLE
抽象小bug，零号银行路线错误冲第二层反复撞墙（带长时间测试的游戏回放）

### ISSUE THREAD

**Issue by Presikid** [sMythicalBird/ZenlessZoneZero-Auto#105]
在[2,1,3]模式中，刷取零号银行进入第一层的休息室时，有极小概率遇到程序bug，啥也不干直接冲到第二层，link直播回放： #https://www.youtube.com/watch?v=I-9ZZ-xXcSk
回放中11时27分09秒~11时47分19秒区间可以查看该bug

**Comment by Presikid** [comment]
备注：这是早上爬起来正好看到的，长时间的测试中可能还有一些其它小bug，不过我没注意到，sugar有兴趣可以到直播回放里乱翻翻，说不定还有意外收获

**Comment by sMythicalBird** [comment]
> 在[2,1,3]模式中，刷取零号银行进入第一层的休息室时，有极小概率遇到程序bug，啥也不干直接冲到第二层，link直播回放： #https://www.youtube.com/watch?v=I-9ZZ-xXcSk 回放中11时27分09秒~11时47分19秒区间可以查看该bug
下次给cmd信息，不看logger看不出来什么原因

**Comment by Presikid** [comment]
> > 在[2,1,3]模式中，刷取零号银行进入第一层的休息室时，有极小概率遇到程序bug，啥也不干直接冲到第二层，link直播回放： #https://www.youtube.com/watch?v=I-9ZZ-xXcSk 回放中11时27分09秒~11时47分19秒区间可以查看该bug
> > 下次给cmd信息，不看logger看不出来什么原因

我猜是图像识别错了，问题不大

**Comment by Presikid** [comment]
issue先开着，等我再遇到补图
