### ISSUE TITLE
适配一下1920*1080吧

### ISSUE THREAD

**Issue by hzr12** [sMythicalBird/ZenlessZoneZero-Auto#108]
适配一下1920*1080吧

**Comment by lazydog28** [comment]
> 适配一下1920*1080吧

游戏窗口分辨率还是屏幕分辨率？

**Comment by lazydog28** [comment]
当前脚本只要求游戏分辨率为1280×720，屏幕分辨率对脚本影响不大

没有适配其他游戏窗口分辨率的计划

**Comment by hzr12** [comment]
窗口分辨率

**Comment by hzr12** [comment]
![image](https://github.com/user-attachments/assets/6f9f7e94-3f2b-41e4-be83-3e48b8a83102)
1280*720有点小
