### ISSUE TITLE
卡在关底事件无法进入

### ISSUE THREAD

**Issue by kebilaoda114514** [sMythicalBird/ZenlessZoneZero-Auto#111]
关底事件识别错误，导致选择不再进入，由于移动采用的是键盘方向键移动，导致再次到达关底无法触发事件，之后便一直卡在这里。
![微信图片_20240803164249](https://github.com/user-attachments/assets/39480ba9-d8df-48eb-948c-e8b8497436a7)

**Comment by sMythicalBird** [comment]
调屏幕缩放，ocr识别应该有问题，第一次进入终点没识别退出了，之后进不去了
