### ISSUE TITLE
地图bug

### ISSUE THREAD

**Issue by Presikid** [sMythicalBird/ZenlessZoneZero-Auto#112]
记得之前好像有人提过，（我忘截屏了），在抽奖区域内，（可以抽4次奖的那个），程序会无法交互出不去，一直卡在对话界面里

**Comment by Presikid** [comment]
好像还没修好

**Comment by sMythicalBird** [comment]
是新的代码吗，这个有人修过了

**Comment by Presikid** [comment]
最新的了，而且感觉就是修了出问题，之前几天都是好的，今天一更新到目前为止一下子爆了3次这个bug

**Comment by sMythicalBird** [comment]
不是加了离开判断吗，那边离开没用吗

**Comment by Presikid** [comment]
没有用，对话框两个选项对吧
第一个是抽奖
第二个是离开
他那个都不点，就卡在对话界面了

**Comment by Presikid** [comment]
> 我也刷不到那个图啊，不知道啥情况，下次遇到改吧

行，看来是我运气不好，昨天连着好几把出了，bug给我硬控住了

**Comment by sMythicalBird** [comment]
> > 我也刷不到那个图啊，不知道啥情况，下次遇到改吧
> 
> 行，看来是我运气不好，昨天连着好几把出了，bug给我硬控住了

那张图直接离开也没用吗，必须抽完奖？

**Comment by Presikid** [comment]
那张图可以不抽奖走人，但是程序既不会点抽奖也不会点离开，就卡在对话界面啥也不干，等到时间到了由于判定为在对话，又不能自动退出重开

**Comment by 871943346** [comment]
旧都列车----腹地
能识别到出去的旗帜，但是那里是没有路的（空格子），然后就会一直在那里撞墙，
他会上下往左边撞墙（上下1格），
往上多几格子就出去了
![8cf309a27c4fc880c0afb48f8343b3f3](https://github.com/user-attachments/assets/fc4cd00f-437f-472d-8499-9cafb1fd985d)

**Comment by sMythicalBird** [comment]
> 旧都列车----腹地
> 能识别到出去的旗帜，但是那里是没有路的（空格子），然后就会一直在那里撞墙，
> 他会上下往左边撞墙（上下1格），
> 往上多几格子就出去了
> ![8cf309a27c4fc880c0afb48f8343b3f3](https://github.com/user-attachments/assets/fc4cd00f-437f-472d-8499-9cafb1fd985d)
> 

代码是什么时候的代码

**Comment by 871943346** [comment]
> > 旧都列车----腹地
> > 能识别到出去的旗帜，但是那里是没有路的（空格子），然后就会一直在那里撞墙，
> > 他会上下往左边撞墙（上下1格），
> > 往上多几格子就出去了
> > ![8cf309a27c4fc880c0afb48f8343b3f3](https://github.com/user-attachments/assets/fc4cd00f-437f-472d-8499-9cafb1fd985d)
> > 
> 
> 代码是什么时候的代码

我的问题
用的昨晚的版本
刚才更新最新的

可以正常使用了
感谢

**Comment by sMythicalBird** [comment]
> > > 旧都列车----腹地
> > > 能识别到出去的旗帜，但是那里是没有路的（空格子），然后就会一直在那里撞墙，
> > > 他会上下往左边撞墙（上下1格），
> > > 往上多几格子就出去了
> > > ![8cf309a27c4fc880c0afb48f8343b3f3](https://private-user-images.githubusercontent.com/53554546/355664063-fc4cd00f-437f-472d-8499-9cafb1fd985d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMDQ0MzgsIm5iZiI6MTcyMzAwNDEzOCwicGF0aCI6Ii81MzU1NDU0Ni8zNTU2NjQwNjMtZmM0Y2QwMGYtNDM3Zi00NzJkLTg0OTktOWNhZmIxZmQ5ODVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA0MTUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5ZGNhM2Y4ZDg0N2QzYzc5MzNkMDEwNDFkODIwYzA2ZmFlZDQ1Y2NmYTU0MjZlNWFiZTVmZGI0ODNjZDBlYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LsmSwQAlHM8ayrgBCfOyqG7y4cDVk1JKi3IXLkoAe3I)
> > 
> > 
> > 代码是什么时候的代码
> 
> 我的问题 用的昨晚的版本 刚才更新最新的
> 
> 可以正常使用了 感谢

昨晚的和现在的没动什么东西，昨晚的代码应该没问题，你后续看看还有没有这种情况把
