### ISSUE TITLE
小白不会解决

### ISSUE THREAD

**Issue by wxdlpxt** [sMythicalBird/ZenlessZoneZero-Auto#114]
from pydirectinput import (
ImportError: cannot import name 'scroll' from 'pydirectinput' (E:\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pydirectinput\__init__.py)
这个报错该怎么弄

**Comment by lazydog28** [comment]
安装错包了，`pydirectinput`的包名是`pydirectinput-rgx`

```
pip install pydirectinput-rgx
````
