### ISSUE TITLE
达到零号业绩上限时会卡住循环

### ISSUE THREAD

**Issue by 30Hzzh** [sMythicalBird/ZenlessZoneZero-Auto#117]
当达到零号业绩上限时，到达指定位置后不会跳出已领取提示，就一直会在图一所示位置左右移动死循环，应该可以优化成退出游戏，并在脚本内提示。
![$XHK T4G0MKC6(D _{HZZ2S](https://github.com/user-attachments/assets/a005f587-f619-4ee3-bd8c-802e109f4b47)
![Snipaste_2024-08-04_18-42-07](https://github.com/user-attachments/assets/7a80300d-57a4-4fcf-b11e-9d9d80553bd1)

**Comment by sMythicalBird** [comment]
刷完了就可以关掉了

**Comment by 30Hzzh** [comment]
有时候挂机出去或者睡觉不知道什么时候刷完

**Comment by 30Hzzh** [comment]
> 刷完了就可以关掉了

有时候挂机出去或者睡觉不知道什么时候刷完
