### ISSUE TITLE
安装依赖时报错

### ISSUE THREAD

**Issue by Yukari42015050831** [sMythicalBird/ZenlessZoneZero-Auto#119]
ERROR: Exception:Traceback (most recent call last): File "E: \ZenlessZoneZero-Auto-master(py310\1ib\site-packages\pip internal\cli\base_conmand. 
py", line 180, in exc_loggling_wrapperstatus = run_func(*args)File "E:\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip _internal\cli\req_conmand. 
py", line 245, in wrapperl return func(self, options, args) File "E:\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pipLinternal\commands\install.py", line 377, in run requirement_set = resolver.
resolve( File "E:\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip internal\resolution\resolvelib\resolver.py", line 95l in resolveresult = self. 
_result = resolver.
resolve(File "E:\ZenlessZoneZero-Auto-master\py310\1ib\site-packages\pipvendor\resolvelib\resolvers.py", line 546, in resolvestate = resolution,resolve(requirements, max_rounds-max_rounds) File "E:\ZenlessZoneZero-Auto-master\py310\1ib\site-packages\pipvendor\resolvelib\resolvers.py", line 427, in resolvefailure_causes = self. 
_attempt_to_pin_criterion(name) File "E:\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pipvendor(resolvelib(resolvers.py", line 239, in _attempt_to_pin_criterioncriteria = self._get_updated_criteria(candidate)File "E:\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pipvendor\resolvelib(resolvers.py", line 230, in _get_updated_criteriaself.
_add_to_criteria(criteria, requirement, parent=candidate) File "E:\ZenlessZoneZero-Auto-master\py310\1ib\site-packages\pip vendor\resolvelib\resolvers,py", line 173, in _add_tl o_criteria
return bool (self._sequence) File "E: \ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py",lline 155, in _boolreturn any(self)File "E:\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates. 
py",lline 143, in (genexpr)line 47, in _iter_builtreturn (c for c in iterator if id(c) not in self._incompatible_ids) File "E:\ZenlessZoneZero-Auto-master\py310\lib\site-packages pip internal \resolution\resolvelib\found_candidates. 
py",lcandidate = func()File "E:\ZenlessZoneZero-Auto-master\py310\1ib\site-packages\pip internal\resolution\resolvelib\factory.py", line 182in _make_candidate_from_linkbase: Optional[BaseCandidate] = self.
_make_base_candidate_from_link( File "E:\ZenlessZoneZero-Auto-master\py310\1ib site-packages\pip internal\resolution resolvelib\factory.py", line 228 in _make_base_candidate_from_linkself.
_link_candidate_cache[link] = LinkCandidate(File "E:\ZenlessZoneZero-Auto-master\py310\1ib\site-packages\pip\_internal\resolution\resolvelib\candidates,py", linel 290, in _init_super().
_init__(File "E:\ZenlessZoneZero-Auto-master\py310\1ib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", linel 156, in_init_self. 
dist=self. 
prepare File "E:\ZenlessZoneZero-Auto-master\py310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates,py", linel 222, in preparedict = celf nrenare dictrihution()

File "importlibl init .py", line 126,in import moduleModuleNotFoundError: No module named mesonpy

**Comment by whx1024** [comment]
按这个修改https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues/113#issuecomment-2267362183
