### ISSUE TITLE
CPU版本运行慢

### ISSUE THREAD

**Issue by Auunes** [sMythicalBird/ZenlessZoneZero-Auto#126]
为啥cpu版本在地图每走一步停差不多10秒才走下一步，这个检测有点慢了吧。战斗倒是正常

**Comment by sMythicalBird** [comment]
cpu虽然慢，不过没这么离谱，你啥时候买的电脑

**Comment by Auunes** [comment]
> cpu虽然慢，不过没这么离谱，你啥时候买的电脑

e31230v2，主力机每次要将画质分辨率缩放调来调去太麻烦了才用的二奶机，这个u是老了点，但是orc识别应该不至于这么慢

**Comment by lazydog28** [comment]
你这个U确实有点老了，OCR识别慢咱们也没啥能优化的办法

**Comment by lazydog28** [comment]
你可以自行尝试更换其他的OCR识别模型或者接口
