### ISSUE TITLE
正常运行，但是出现无法识别的标识

### ISSUE THREAD

**Issue by wxdlpxt** [sMythicalBird/ZenlessZoneZero-Auto#132]
| DEBUG    | handle.others:grid_map:64 - 未识别到地图信息
| DEBUG    | handle.others:grid_map:70 - 未找到路径
hdr也关了，还是出现

**Comment by lazydog28** [comment]
是偶尔出现这个问题还是一直无法寻路？

**Comment by wxdlpxt** [comment]
> 是偶尔出现这个问题还是一直无法寻路？

这个错误每次都会出现，不过能完成自动寻路，就是有时会卡死
![1723028018153](https://github.com/user-attachments/assets/a83628c0-c249-40ee-b161-54487a313485)

**Comment by lazydog28** [comment]
偶尔出现属于正常，卡死不正常。
[推荐游戏设置](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/wiki/%E6%8E%A8%E8%8D%90%E6%B8%B8%E6%88%8F%E8%AE%BE%E7%BD%AE)

**Comment by wxdlpxt** [comment]
> 偶尔出现属于正常，卡死不正常。 [推荐游戏设置](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/wiki/%E6%8E%A8%E8%8D%90%E6%B8%B8%E6%88%8F%E8%AE%BE%E7%BD%AE)

好的
