### ISSUE TITLE
寻路改进优化设想及模拟操作存在的问题

### ISSUE THREAD

**Issue by KrOik** [sMythicalBird/ZenlessZoneZero-Auto#133]
您好，开发者！该脚本为日常上提供了极大的便利与帮助，同时也迎合了许多玩家的需求，感谢您！
我在近几天体验了一下该脚本，发现一部分其中可以优化的地方。在我个人的设想中，若是以您的技术达成以下改进，将有显著提升该项目的可能性。包括体验和使用上的改进。
使用上存在的改进设想：
1.加载时间过长，能否优化寻路算法？在进行图形识别的时候，需要完成地图的判断，但在判断完地图后的操作中存在明显的一步一次的较长停顿。是否能过通过单次识别后进行路径的规划从而实现快速的操作输入完成时间上的优化呢？例如，标记无需操作事件格后，径直走过即可。
2.在进行对话窗口（事件格的交互）时，页面右侧的文字显示总是要等待加载完后才能进行下一步操作，能否实现快速完成交互？例如，在完成识别事件格：零号银行时，在对话显示窗口处进行一定次数的点击跳过对话，再在要执行的操作处完成点击。
3.鸣徽的选择和邦布的选择停留较久，能否直接点击选择而不用进行判断进而优化整体流程时长？因为对于部分练度足够的玩家来说，邦布和鸣徽在速刷时起到的作用微乎其微，反而是起到了“减速带”的负面效果。
体验上存在的问题：
1.在模拟玩家操作时，鼠标总是在完成操作后瞬移到窗口左上角。在进行操作时，鼠标也是以“定位-移动到目标位置”瞬间完成的。我仍然担心可能日后会出现操作检测，从而导致不必要的禁封。所以能否模拟真人在进行操作时的鼠标轨迹，进行鼠标路径的优化呢？在战斗时也存在视角移动过于机械的问题，希望能得到优化。
同时我也有点担心，希望本脚本是作为辅助而非外挂，仅进行一种技术上可能性的探索而非真正落地从而被不幸的“介入”而消失。
我很抱歉，基于自身技术水平有限，无法深入参与您所需改进的程序。尽管如此，我愿意从心灵上支持和鼓励您。我深信，您定能将这一程序不断完善，取得更大的成就。
若我的一些初步想法过于大胆或超出正常实现范围，还请您多多包涵。希望您能早日实现您的愿景！祝愿您的程序越做越好，未来更上一层楼！
谢谢您的努力与付出！祝一切顺利！

**Comment by sMythicalBird** [comment]
您好，感谢您的真诚反馈，你所提的问题很合理，但目前来说不是一时半会可以解决的，先回答你的改进设想
1、你所说的加载时间过长与寻路算法无关，寻路算法一次bfs耗时非常短，在寻路算法之前进行地图识别的部分，这部分用的训练好的模型，实际耗时也不长，真正用时长的是ocr识别，大部分耗时都在这上面，如果是cpu版本时间会更久。至于你说的判断玩地图存在明显的一步一次的问题，这主要是为了提高程序的容错性，只做一次识别可以做到，但随之而来的问题是整张地图的寻路不可控，容易出现意外，尤其是终点第一次没识别到，整个路径都是错的，全通模式还要优先找队友，支援事件会调整状态参数，这些问题都会导致整个路径的变动，并且单次识别在处理的时候就很难讲处理逻辑拆分的清楚，后续优化也有问题。关于标记无需操作的事件格，这个确实是可以的，现在权重数量少，后面分的细一点是是可以减少这方面事件，目前未这么做的具体原因在第二点提及
2、对话事件之所以满，是因为采取的通用事件进行了多次ocr，从而导致每次对话点击耗时都很久，为什么不进行一定次数呢，本项目不是连点器，进行一定次数固然更快，但相应的，一旦出现意外情况很有可能造成整个程序卡住的情况。快速交互可以做到吗，答案是可以，之所以没那么多是因为事件实在是太多了，个人时间真的有限，平时也比较忙，实在没办法一个一个事件整理，你可以发现全通模式只支持列车，因为其他地图的事件我都没怎么搜集，要想去掉通用处理就要整理所有事件，整个工作量太大了，等后面有时间再做把。
3、直接点击选择也要找到选择在哪，1中说过ocr耗时久，这就是原因，当然你可能想问知道要选择的话就直接点不就行了，但是选择出现的情况太多了，加上有个不可触碰的侵蚀在，这方面的处理就只能慎重一点。另外所有模式共用的一套逻辑，速刷已经对第二层进行过加快处理了，不可能对所有模式分开各写一套逻辑，那样代码复用性就太差了，出问题每个模式也都要改。
对于体验上的问题：
1、鼠标移动这个不用担心，可以说除了战斗逻辑是固定了事件，其他情况根本没什么固定时间，前面你提到了事件处理时间久，这个ocr的耗时的随机性应该没有检测程序可以预测把。点击的时间倒是可以加点随机值，这个问题不大。战斗的视角移动问题你应该指的是地图中的寻路，但是现在问题根本不是有没有机械的情况，而是目前就没做好，我现在也没有好的想法，zzz战斗没有小地图，部分地图会卡住的情况都没法解决
本项目未涉及任何游戏参数和内存的改动，以后也不准备去碰这些东西，这个你可以放心，你提的问题很好，我也确实想解决。但是工作量太大了，暂时只能先这样，后续开发会围绕战斗模块和项目的ui界面进行，事件优化可能还要过很久，我最近也要秋招了，暂时确实没那么多时间处理问题，等下半年闲下来再做吧

**Comment by sMythicalBird** [comment]
你可以看到源码对部分处理里加了很多延迟，你可以适当去掉一部分或者缩短时间，因为使用者的硬件设备不一，有很多延迟是用来保容错的。我在写的时候没用到这么多，然而测试的时候发现各种问题频发，这些延迟也是不得已才加的，你电脑性能够好的话可以适当删减或下调一部分延迟
