### ISSUE TITLE
终点战斗事件可能取消导致重复循环

### ISSUE THREAD

**Issue by KUOD547** [sMythicalBird/ZenlessZoneZero-Auto#134]
![屏幕截图 2024-08-08 135135](https://github.com/user-attachments/assets/60f6572e-6688-422c-a7bd-552c899c66e7)
遇到好几次了，他有时就不会进终点战斗然后一直来回走格子

**Comment by KUOD547** [comment]
[logger.log](https://github.com/user-attachments/files/16538308/logger.log)

**Comment by sMythicalBird** [comment]
屏幕缩放多少

**Comment by KUOD547** [comment]
缩放120%，我屏幕是1920*1200

**Comment by sMythicalBird** [comment]
> 缩放120%，我屏幕是1920*1200

看readme的要求，改完再跑，有问题再来问
