### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by JoshCai233** [sMythicalBird/ZenlessZoneZero-Auto#138]
![QQ截图20240808223959](https://github.com/user-attachments/assets/479e8c32-f899-4afc-aa82-26d32dbfc516)

**Comment by lazydog28** [comment]
请使用`python3.10`以上的python版本

**Comment by JoshCai233** [comment]
好的，谢谢大佬
