### ISSUE TITLE
猫又特殊事件问题

### ISSUE THREAD

**Issue by owwkmidream** [sMythicalBird/ZenlessZoneZero-Auto#14]
碰到如图所示的猫又特殊事件后，由于没有离开选项，脚本会卡主无法执行。
![image](https://github.com/user-attachments/assets/60d6eb5f-b429-4acb-8407-b4346b5d3463)

**Comment by owwkmidream** [comment]
#15

**Comment by xiaoxinxinerd** [comment]
"https://file.caiyun.fun/download/zzz/"这个网页的文件404了，要在哪里找到下载？

**Comment by sMythicalBird** [comment]
这个pr先等一下，马上会发下个版本，合到下个版本里

**Comment by owwkmidream** [comment]
> 这个pr先等一下，马上会发下个版本，合到下个版本里

ok
