### ISSUE TITLE
在打第三章地图的时候，跟踪时会卡地图

### ISSUE THREAD

**Issue by LOvivi-648** [sMythicalBird/ZenlessZoneZero-Auto#141]
![QQ图片20240809005756](https://github.com/user-attachments/assets/c3ae4a98-b29c-4dfc-9d9c-666f71f88333)

**Comment by sMythicalBird** [comment]
> ![QQ图片20240809005756](https://github.com/user-attachments/assets/c3ae4a98-b29c-4dfc-9d9c-666f71f88333)
> 

卡地图就等他退了
