### ISSUE TITLE
卡在特殊事件一个小时

### ISSUE THREAD

**Issue by 30Hzzh** [sMythicalBird/ZenlessZoneZero-Auto#143]
选项为通关列车，核心难度，进入特殊关卡卡住1h，如图所示
![}{~G3{IPWD5D 7{G~A`Q5VK](https://github.com/user-attachments/assets/9e9d00d0-4eee-4698-9fcc-f94da8d2b779)
![P}I~SZ(CNR4C6I~UDHI7H{V](https://github.com/user-attachments/assets/b7a98057-ea8d-4ac5-9922-f723ca4ef5a6)
![T%64LQ ((T7%3~4AZ( KGQD](https://github.com/user-attachments/assets/4cc5ffaa-61ef-41d9-8a0f-d1b46ff5f15b)

**Comment by sMythicalBird** [comment]
要怎么出去，可以直接离开吗

**Comment by sMythicalBird** [comment]
离开之后是什么样子，截下图

**Comment by 30Hzzh** [comment]
> 要怎么出去，可以直接离开吗

可以的
