### ISSUE TITLE
刷零号业绩模式设置为自动进行2层

### ISSUE THREAD

**Issue by movieuu** [sMythicalBird/ZenlessZoneZero-Auto#145]
现在刷零号业绩最好的方式是旧都列车 腹地 连打两层 给60业绩 效率高很多

**Comment by sMythicalBird** [comment]
> 现在刷零号业绩最好的方式是旧都列车 腹地 连打两层 给60业绩 效率高很多

打两层就自己改下源码，为保证程序稳定性，刷列车前线是最快的
