### ISSUE TITLE
參考一下隔壁人家鳴潮的後台自動刷龜吧 

### ISSUE THREAD

**Issue by lavender7410** [sMythicalBird/ZenlessZoneZero-Auto#146]
人家能實現後台刷BOSS 是否能參考一下

**Comment by lazydog28** [comment]
没法参考，鸣潮和绝区零的事件处理方式不一样，鸣潮会对传入的事件进行处理，因此可以后台运行，鸣潮及米哈游其他游戏都是直接读取硬件的事件池，不对传入的事件进行处理，所以没法后台运行
