### ISSUE TITLE
遇到雙刀哥死亡率幾乎是100%

### ISSUE THREAD

**Issue by lavender7410** [sMythicalBird/ZenlessZoneZero-Auto#147]
難度5
進場的時候只有艾蓮一個人

**Comment by sMythicalBird** [comment]
怎么没找队友，不是找了吗，不过打不过也有练度问题，群里有人50级已经能单通核心了

**Comment by lavender7410** [comment]
> 怎么没找队友，不是找了吗，不过打不过也有练度问题，群里有人50级已经能单通核心了

．．雖然已經挺久的　但我手操也可以啊= = 問題是這個自動戰鬥通常都在挨打阿
