### ISSUE TITLE
卡在 添加页面：打不过怪

### ISSUE THREAD

**Issue by 1723572491** [sMythicalBird/ZenlessZoneZero-Auto#148]
![image](https://github.com/user-attachments/assets/b474112f-374c-45ce-aabd-490e97cb61aa)
![image](https://github.com/user-attachments/assets/b3d33ee4-7354-489b-8940-d1454162aae9)

**Comment by 1723572491** [comment]
![Uploading 微信截图_20240810171523.png…]()

**Comment by sMythicalBird** [comment]
游戏窗口不要最小化，重新运行
