### ISSUE TITLE
部分事件卡住不做选择

### ISSUE THREAD

**Issue by Daydreamer114** [sMythicalBird/ZenlessZoneZero-Auto#149]
![image](https://github.com/user-attachments/assets/750e430e-54ae-4194-831b-8b56956e6b56)
请问事件选项使用的是文字识别+打表匹配吗？如果是的话请问在哪个文件？遇到owner没写的也可以pr进来

**Comment by Daydreamer114** [comment]
![image](https://github.com/user-attachments/assets/64bef241-67af-4fe3-a239-1639f4c5d8d0)
还有这个，可以识别一下右上角的叉号

**Comment by Daydreamer114** [comment]
![image](https://github.com/user-attachments/assets/c8dc3e20-b10b-4b0d-8525-88af73f44b76)

**Comment by Daydreamer114** [comment]
![image](https://github.com/user-attachments/assets/b5a697bc-3aea-456b-a75e-7abecd23b92d)

**Comment by sMythicalBird** [comment]
有没有可能，你说的事件都是可以处理的，屏幕缩放调了吗
