### ISSUE TITLE
远程主机强迫关闭了一个现有的连接

### ISSUE THREAD

**Issue by xiaoxinxinerd** [sMythicalBird/ZenlessZoneZero-Auto#16]
('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
提示这个应该怎么解决？

**Comment by lazydog28** [comment]
网络问题，换个网络或者重新试试

**Comment by lbls741** [comment]
似乎可以手动补全缺失的文件，[这里](https://[file.caiyun.fun/download/zzz/filelist.txt](https://file.caiyun.fun/download/zzz/filelist.txt))是官方提供的文件清单
把下载到7个的文件放在"程序目录\download"目录下，然后再试试?
