### ISSUE TITLE
寻路逻辑在进图后的第一步踩怪脸上

### ISSUE THREAD

**Issue by MH-Leon** [sMythicalBird/ZenlessZoneZero-Auto#161]
列车图刷业绩/银行, 第一层遇小怪会自动炸掉, 但遇到下面这种开局时, 寻路逻辑大概率第一步直接向终点走(上或右), 然后踩怪脸上当场开战
![屏幕截图 2024-08-12 020524](https://github.com/user-attachments/assets/0d49f945-ecae-42ed-a918-fe270c70b2ba)
刷业界/银行模式貌似对呼叫增援事件的优先级较低, 如果事件不刷在去终点的路上, 就不会去触发, 比如上图

另外这边有两点小建议
自动开二倍速, 时间能短不少, 尝试了一下, 在grid_map()里判断首次进图, 点击 "^当前层数"左边90像素的地方一次, 能够稳定开启; 90我是盲猜的, 我是4k+150%缩放, 这个90不同缩放系数可能不适用; 当前版本战斗会断二倍速, 还要额外判断战斗后, 但1.1版本好像就修了

通用点击事件的处理那里, 如果上一个页面不是通用点击事件，那么等待一秒, 改为狂拍空格2秒, 可以快速过完研究者的屁话, 对各种事件的介绍文本都好使, 还不会误触选项

**Comment by sMythicalBird** [comment]
刷业绩为什么要队友，没必要，都是秒。等待换空格在遇到特殊区域的时候会出问题，这个目前还没有应对办法，所以暂时不做更改。二倍速暂时不加，文字有概率影响格子识别，所以未作处理。
至于炸弹，不应该出现这种情况，你是gpu版的吗，电脑配置如何

**Comment by MH-Leon** [comment]
GPU版本，4090，应该不存在性能问题

**Comment by sMythicalBird** [comment]
就因为你性能太好才有这种情况，识别太快，动画还没加载完就开始识别了所以出问题，你可以自己在代码里加点延迟
