### ISSUE TITLE
提升CPU的OCR 速度

### ISSUE THREAD

**Issue by JerryLingjieMei** [sMythicalBird/ZenlessZoneZero-Auto#162]
每次CPU的OCR都要经过3-4秒才能响应，一定程度上拖累了刷空洞奖励的节奏。是否可以使用更加快速的model或processing使得事件选择更加快速？

**Comment by sMythicalBird** [comment]
那你可以帮我找个更好的模型，还有cpu不至于查到34秒这么久吧，多少年了

**Comment by JerryLingjieMei** [comment]
> 那你可以帮我找个更好的模型，还有cpu不至于查到34秒这么久吧，多少年了

是3到4秒 但应该可以更快

**Comment by lazydog28** [comment]
正常CPU进行OCR识别不会用这么长时间，你的CPU是什么型号的？

当前中文OCR识别运行速度、识别精度最好应该就是当前使用的paddleocr模型了，我也不知道有哪些更合适的模型，如果有更好的模型可以推荐以下
