### ISSUE TITLE
刷业绩进入第二关直接卡住，不会动

### ISSUE THREAD

**Issue by smallmj** [sMythicalBird/ZenlessZoneZero-Auto#166]
![Screenshot_20240812_180102_youqu.android.todesk.jpg](https://github.com/user-attachments/assets/8f4d1f6c-c771-4920-8e36-a943049af4a0)

**Comment by lazydog28** [comment]
根据日志信息判断是无法识别到人物当前位置，这个问题暂时没有方案，请自行检查是否开启了防蓝光等影响屏幕颜色的功能，高分辨率的屏幕请自行尝试修改屏幕缩放比例来尝试，
