### ISSUE TITLE
部分关卡战斗间无法正常寻路

### ISSUE THREAD

**Issue by chillpoints** [sMythicalBird/ZenlessZoneZero-Auto#169]
视频链接：https://pan.hotpe.top/s/7XQTv
解决方法：
1. 如果对准了目标的灰色小球标识，但是一段时间后（如60秒）仍未进入战斗，则向右/左偏移镜头一定角度，前进10s后再对齐灰色小球标识。
2. 在前进时，保持不断左右摇摆。（按w的同时轮流点按a和d）
3. 收集所有可能卡住的地方，比如视频中的地方，我已经从1.0卡到2.2了，图像识别遇到这些地方就启动提前录制好的操作，只要灵敏度一样就可以适用所有人。

**Comment by sMythicalBird** [comment]
到时间会退，最近两个版本没时间处理。你可以先做，效果好的话提一份pr
