### ISSUE TITLE
被卡在地图中间不进入战斗时，不会退出，就一直卡住了

### ISSUE THREAD

**Issue by chillpoints** [sMythicalBird/ZenlessZoneZero-Auto#170]
解决方法：
加一个计时器，开启这一轮后1800秒内没有完成任务，就退出

**Comment by lazydog28** [comment]
没有看懂你的问题描述，请尽量提供出问题时的截图，包含日志及游戏窗口

**Comment by lazydog28** [comment]
如果你是说在卡在战斗地图里的话，现在配置文件里已经有最大战斗时间，超过最大战斗时间就会退出

如果你是说在卡在走格子地图里的话，配置文件里也已经有最大时间，超过最大时间就会退出

如果是其他问题请重新打开问题
