### ISSUE TITLE
[Bug]: 打完了一次之后重新进入会自动退出

### ISSUE THREAD

**Issue by Yukari42015050831** [sMythicalBird/ZenlessZoneZero-Auto#177]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.2 (Default)

### bug情况描述

刷材料本或者仪器本都会这样，刷完了一次之后再次进入会自动退出。

### 上传截图

![1](https://github.com/user-attachments/assets/ef518e7c-8600-4286-83d7-8edf2c436f14)

**Comment by QuerXD** [comment]
做了刷体力的模式吗？

**Comment by sMythicalBird** [comment]
> 做了刷体力的模式吗？
战斗还没独立出来，目前不支持

**Comment by sMythicalBird** [comment]
这是什么问题，截一下画面
