### ISSUE TITLE
建议增加选项：刷零号业绩时一局拿完两层的业绩后再开下一把

### ISSUE THREAD

**Issue by Happylifezzq** [sMythicalBird/ZenlessZoneZero-Auto#178]
1.1版本大幅增加了第二层打完后可获取的零号业绩数量（由40个增加到120个），第一层打完的奖励仅从20增加到30。现在打完第二层拿到后再重开刷业绩，效率可能更高。

**Comment by 1714775263** [comment]
有些地方会卡主  就左上角那个容易完成 但是还是会有些bug 接受代理人可能会出问题 最好的办法就是 代理人不能多设置3个

**Comment by sMythicalBird** [comment]
下个版本
