### ISSUE TITLE
非地图原有站斗格无法寻路。

### ISSUE THREAD

**Issue by Zimocen** [sMythicalBird/ZenlessZoneZero-Auto#18]
部分战斗来自事件格随机出来。战斗有多个场景需要寻路，无法自动寻路，会卡在墙角。
不知道通过识别寻路的灰色指示圆点的相对位置，是否能实现自动寻路。

**Comment by sMythicalBird** [comment]
绝区零没小地图，路径上会有障碍物挡住前进，暂时先搁置，遇到需要跑图的战斗到时间会退出，后面再想办法处理，
