### ISSUE TITLE
[Bug]: 2.2.1bug，进入红光战斗模式之后不会回到角色战斗模式

### ISSUE THREAD

**Issue by zidianzhimeng** [sMythicalBird/ZenlessZoneZero-Auto#182]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.2 (Default)

### bug情况描述

战斗循环中，最开始会进入一次角色战斗模式，之后就站在原地发呆，只会触发红光，黄光战斗模式，具体的可以看日志

### 上传截图

![91JZYY%MLI5T3Y1EI `N3A](https://github.com/user-attachments/assets/a15bac8e-0630-46af-a042-9a030e2091cd)

**Comment by sMythicalBird** [comment]
是新代码还是2.2

**Comment by miciix** [comment]
我也有这个问题， 177行加个execute_tactic_event.set() 就好了。
https://github.com/sMythicalBird/ZenlessZoneZero-Auto/blob/4462af7437edb18ebe01a9fcc158bcf2c6ff6d7e/fight/fight_zero.py#L110-L118

**Comment by zidianzhimeng** [comment]
新代码，老的没这个问题

**Comment by flashzs** [comment]
更新了2.2.1之后我也有进红光模式发呆的情况，但是不是每次都触发。

**Comment by sMythicalBird** [comment]
> 我也有这个问题， 117行加个execute_tactic_event.set() 就好了。
> 
> https://github.com/sMythicalBird/ZenlessZoneZero-Auto/blob/4462af7437edb18ebe01a9fcc158bcf2c6ff6d7e/fight/fight_zero.py#L110-L118

红光并没有阻塞执行啊，战斗逻辑应该没受影响才对啊

**Comment by sMythicalBird** [comment]
> > 我也有这个问题， 117行加个execute_tactic_event.set() 就好了。
> > https://github.com/sMythicalBird/ZenlessZoneZero-Auto/blob/4462af7437edb18ebe01a9fcc158bcf2c6ff6d7e/fight/fight_zero.py#L110-L118
> 
> 红光并没有阻塞执行啊，战斗逻辑应该没受影响才对啊

我测试的时候也很正常啊

**Comment by zidianzhimeng** [comment]
> 我也有这个问题， 117行加个execute_tactic_event.set() 就好了。
> 
> https://github.com/sMythicalBird/ZenlessZoneZero-Auto/blob/4462af7437edb18ebe01a9fcc158bcf2c6ff6d7e/fight/fight_zero.py#L110-L118

我照着这个改了，确实正常了

**Comment by sMythicalBird** [comment]
> > 我也有这个问题， 117行加个execute_tactic_event.set() 就好了。
> > https://github.com/sMythicalBird/ZenlessZoneZero-Auto/blob/4462af7437edb18ebe01a9fcc158bcf2c6ff6d7e/fight/fight_zero.py#L110-L118
> 
> 我照着这个改了，确实正常了

我周末再看看逻辑吧，但按道理红光并不会暂停进程，看看是不是其他地方导致的，不行就再加一层判断

**Comment by IsSmallPigPig** [comment]
由于长时间没有新的补充。该 Comment 被关闭
