### ISSUE TITLE
能否给刷业绩和银行的模式也加上在第一关招募队友的选项

### ISSUE THREAD

**Issue by smallmj** [sMythicalBird/ZenlessZoneZero-Auto#189]
经常第一关打boss打不到s，然后就在s门那里卡很久

**Comment by sMythicalBird** [comment]
你练度得多低啊，列车前线都打不过

**Comment by smallmj** [comment]
> 你练度得多低啊，列车前线都打不过

新手。。。角色刚到50级。。。关键是远程挂机的电脑比较拉跨，只能cpu模式，识别有点慢，经常红光躲闪不了挨打。。。但是如果有队友，识别黄光的概率就高很多，不知道为啥

**Comment by sMythicalBird** [comment]
> > 你练度得多低啊，列车前线都打不过
> 
> 新手。。。角色刚到50级。。。关键是远程挂机的电脑比较拉跨，只能cpu模式，识别有点慢，经常红光躲闪不了挨打。。。但是如果有队友，识别黄光的概率就高很多，不知道为啥

50级不至于打前线还打不过吧

**Comment by smallmj** [comment]
不是打不过，是经常不能打到s，导致后面开不了s门，拿不到业绩

**Comment by sMythicalBird** [comment]
> 不是打不过，是经常不能打到s，导致后面开不了s门，拿不到业绩

下版本把队友设为自选

**Comment by IsSmallPigPig** [comment]
由于长时间没有新的消息，该 Comment 被关闭
