### ISSUE TITLE
能开发刷两层吗空洞吗？现在调整了奖励，两层一共给150

### ISSUE THREAD

**Issue by Inscher** [sMythicalBird/ZenlessZoneZero-Auto#191]
旧都列车复地，第一层可以直接套用。第二层用炸弹炸个小怪后直接打BOSS，再拿第二层业绩走人。一套下来150个业绩

**Comment by sMythicalBird** [comment]
> 旧都列车复地，第一层可以直接套用。第二层用炸弹炸个小怪后直接打BOSS，再拿第二层业绩走人。一套下来150个业绩

下个版本会加
