### ISSUE TITLE
[Bug]: 失焦后无法继续点击

### ISSUE THREAD

**Issue by ERRORawa** [sMythicalBird/ZenlessZoneZero-Auto#195]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.2 (Default)

### 系统版本

Windows 11

### bug情况描述

当游戏窗口不处于焦点状态时脚本的点击不会生效，只有重新点击游戏窗口让窗口处于焦点才能正常点击
向日葵远程桌面的时候游戏经常会失焦，导致脚本卡着没法继续执行。

### 上传截图

<img width="837" alt="mmexport1723924666922" src="https://github.com/user-attachments/assets/ef1204f8-b3f7-43c3-83b7-cf1093182c58">

**Comment by IsSmallPigPig** [comment]
窗口不在焦点咋点击）你要不用 watt tooikit 给它强行置顶一下

**Comment by ERRORawa** [comment]
> 窗口不在焦点咋点击）你要不用 watt tooikit 给它强行置顶一下

正常鼠标操作不应该是点击之后会把点的位置变成焦点的吗（

**Comment by IsSmallPigPig** [comment]
另外你为什么不用推荐的方案要用向日葵）

**Comment by ERRORawa** [comment]
> 另外你为什么不用推荐的方案要用向日葵）

我也不是时刻守在电脑前，不在一个wifi下只能内网穿透或者直接用其它远程桌面软件（

**Comment by sMythicalBird** [comment]
远程出的问题自己解决，现在只解决本机出现的bug

**Comment by ERRORawa** [comment]
好吧

**Comment by xuehantian** [comment]
您好，请问这个问题解决了吗，我使用Moonlight串流也遇到了同样的问题

**Comment by xuehantian** [comment]
可以尝试在代码里面修改“和高板对话”对应部分的代码，添加一个鼠标点击功能以确保每一次都激活一下窗口，我对着修改的代码如下：
@task.page(name="高坂对话", target_texts=["高坂"])
def action(positions: Dict[str, Position]):
    for i in range(5):
        mouseDown()
        time.sleep(0.1)
        mouseUp()
        time.sleep(0.1)
        control.press("space", duration=0.1)
        time.sleep(0.1)
        control.press("1", duration=0.1)
        time.sleep(0.1)
可以看到，我多增加了：
        mouseDown()
        time.sleep(0.1)
        mouseUp()
        time.sleep(0.1)
这一部分模拟鼠标点击一下的代码，修改之后暂时没有出现窗口失去焦点的情况。
