### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by half-drop** [sMythicalBird/ZenlessZoneZero-Auto#196]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.2 (Default)

### 系统版本

Windows 10

### bug情况描述

进入战斗不会打怪，所有的设置都是按推荐的

### 上传截图

![image](https://github.com/user-attachments/assets/2a084e53-dc0f-43a2-8e4c-dec8be7671f4)

**Comment by lazydog28** [comment]
战斗是用识别屏幕中的`Space`切人键来判断的。你设置切人第二按键后，战斗场景中切人按钮就显示为你设置的那个键了。
