### ISSUE TITLE
[Bug]: 施工废墟休息层 未找到路径

### ISSUE THREAD

**Issue by ERRORawa** [sMythicalBird/ZenlessZoneZero-Auto#197]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.2 (Default)

### bug情况描述

全通模式每次一到这地方就找不到路径了，只能手动前往下一层

### 上传截图

<img width="1676" alt="05d13d77dd0f2f54ac044e567f37973d" src="https://github.com/user-attachments/assets/3529c652-b0b2-44bf-a178-959f372ff91e">

**Comment by IsSmallPigPig** [comment]
您好，很遗憾了解到您无法正常使用我们的脚本
你是否有修改过程序脚本呢？在重启脚本后，能否正常使用该功能？

**Comment by ERRORawa** [comment]
> 您好，很遗憾了解到您无法正常使用我们的脚本 你是否有修改过程序脚本呢？在重启脚本后，能否正常使用该功能？

没修改过，至于is qi

**Comment by ERRORawa** [comment]
> 您好，很遗憾了解到您无法正常使用我们的脚本 你是否有修改过程序脚本呢？在重启脚本后，能否正常使用该功能？

重启也不行，还是未找到路径
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/3a2c34d2-0f0e-4fd0-83dc-3a4b82669acf">

**Comment by sMythicalBird** [comment]
> > 您好，很遗憾了解到您无法正常使用我们的脚本 你是否有修改过程序脚本呢？在重启脚本后，能否正常使用该功能？
> 
> 重启也不行，还是未找到路径
> <img width="1680" alt="image" src="https://github.com/user-attachments/assets/3a2c34d2-0f0e-4fd0-83dc-3a4b82669acf">
> 

换2.3选全体模式(带业绩版)等会发

**Comment by ERRORawa** [comment]
2.3全通带业绩模式还是 未找到路径
![WechatIMG3445](https://github.com/user-attachments/assets/0b2a61b9-b1e0-4153-bbd3-2a5e6eebcf7c)
