### ISSUE TITLE
[Bug]: 入场时不战斗或中途停止战斗

### ISSUE THREAD

**Issue by caobao7** [sMythicalBird/ZenlessZoneZero-Auto#198]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.2 (Default)

### 系统版本

Windows 10

### bug情况描述

execute_tactic_event这个标记应当在进入fight_login时就需要set。否则需要触发闪避模式时才会主动set第一次。

**Comment by IsSmallPigPig** [comment]
请上传截图，补充信息

**Comment by sMythicalBird** [comment]
这个确实忽视了，感谢指出
