### ISSUE TITLE
[BUG] 砖块判定

### ISSUE THREAD

**Issue by LINKlang** [sMythicalBird/ZenlessZoneZero-Auto#20]
好像没给可破碎的砖块做判断，如果在路上碰到砖块就不会打破了

**Comment by LINKlang** [comment]
补充：看了下录屏，好像是少走了一步

**Comment by sMythicalBird** [comment]
这部分做过，之前是全局bfs，给格子定义撞击次数，不过好像不稳定，这版不改了，下个版本重新设计了路径搜索，等下一版吧
