### ISSUE TITLE
[Bug]: 序列化刷空洞

### ISSUE THREAD

**Issue by JerryLingjieMei** [sMythicalBird/ZenlessZoneZero-Auto#201]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.2 (Default)

### bug情况描述

从今天起每周刷两次核心空洞即可获得所有奖励。是否可以修改config.yaml 使得可以首先刷两次列车核心通关，再刷数次列车前线刷满业绩？

**Comment by sMythicalBird** [comment]
> ### 请确保您已经阅读并同意以下要求
> 
> - [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
> - [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
> - [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
> - [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理
> 
> ### 项目版本
> 
> v2.2 (Default)
> 
> ### 系统版本
> 
> _No response_
> 
> ### bug情况描述
> 
> 从今天起每周刷两次核心空洞即可获得所有奖励。是否可以修改config.yaml 使得可以首先刷两次列车核心通关，再刷数次列车前线刷满业绩？
> 
> ### 上传截图
> 
> _No response_

那你为什么不用2.3呢

**Comment by JerryLingjieMei** [comment]
> > ### 请确保您已经阅读并同意以下要求
> > 
> > * [x]  我已阅读项目使用说明，并且按照要求更改了游戏配置
> > * [x]  我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
> > * [x]  我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
> > * [x]  我已经知晓并同意，若该问题与程序无关，将不会被处理
> > 
> > ### 项目版本
> > v2.2 (Default)
> > ### 系统版本
> > _No response_
> > ### bug情况描述
> > 从今天起每周刷两次核心空洞即可获得所有奖励。是否可以修改config.yaml 使得可以首先刷两次列车核心通关，再刷数次列车前线刷满业绩？
> > ### 上传截图
> > _No response_
> 
> 那你为什么不用2.3呢
2.3 尚不支持动态调节空洞难度，需要中途手动修改配置文件

**Comment by sMythicalBird** [comment]
> > > ### 请确保您已经阅读并同意以下要求
> > > 
> > > * [x]   我已阅读项目使用说明，并且按照要求更改了游戏配置
> > > * [x]   我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
> > > * [x]   我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
> > > * [x]   我已经知晓并同意，若该问题与程序无关，将不会被处理
> > > 
> > > ### 项目版本
> > > v2.2 (Default)
> > > ### 系统版本
> > > _No response_
> > > ### bug情况描述
> > > 从今天起每周刷两次核心空洞即可获得所有奖励。是否可以修改config.yaml 使得可以首先刷两次列车核心通关，再刷数次列车前线刷满业绩？
> > > ### 上传截图
> > > _No response_
> > 
> > 
> > 那你为什么不用2.3呢
> > 2.3 尚不支持动态调节空洞难度，需要中途手动修改配置文件

自己改吧
