### ISSUE TITLE
[Bug]: 舊都列車:核心 卡住

### ISSUE THREAD

**Issue by lavender7410** [sMythicalBird/ZenlessZoneZero-Auto#203]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.2 (Default)

### bug情况描述

使用2.3 地圖卡住 一直往左走

### 上传截图

![image](https://github.com/user-attachments/assets/38b22ebf-8e9d-4518-a437-dfba3d615a00)

**Comment by sMythicalBird** [comment]
这张新图，没数据集

**Comment by lavender7410** [comment]
以及使用目前看到 來卡恩跟蒼角都會選擇在2號位置 而不是像之前蒼角會選擇3號位置 所以戰鬥中會看到萊卡恩跟蒼角切來切去不用艾蓮

**Comment by sMythicalBird** [comment]
换2.3.1
