### ISSUE TITLE
[Bug]: 在获得侵蚀破坏欲时卡界面

### ISSUE THREAD

**Issue by whx1024** [sMythicalBird/ZenlessZoneZero-Auto#204]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.2 (Default)

### bug情况描述

2.3。在获得侵蚀，破坏欲：休息区和及时补给无法回复生命值，卡选择界面。群里有人反映类似问题，我也遇到了

### 上传截图

![f520420a4eccbcd5d000f653d6e7e2f](https://github.com/user-attachments/assets/cfd55523-bdcc-4654-ba0a-c40998c0accc)
![2024-08-19](https://github.com/user-attachments/assets/83235b55-9862-4323-8459-b0646462f7e6)

**Comment by sMythicalBird** [comment]
这bug也是绝了
