### ISSUE TITLE
[Bug]: 旧都列车:内部  地图遇到卡关位置

### ISSUE THREAD

**Issue by xwy231321** [sMythicalBird/ZenlessZoneZero-Auto#205]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.2 (Default)

### 系统版本

Windows 11

### bug情况描述

版本为2.3，地图为  旧都列车 内部  ，模式选择为 4：全通关(拾取业绩,级别不够会退出)，在此页面出生点为右上角，随后会循环尝试往下运动，在关掉重开框架后，依旧是持续往下运动，陷入死循环

### 上传截图

![Snipaste_2024-08-19_22-19-47](https://github.com/user-attachments/assets/21d31436-bf54-409a-84e7-057b3c6e7cf2)
![Snipaste_2024-08-19_22-22-45](https://github.com/user-attachments/assets/e144a2e8-39c2-427b-9fce-ce4373116fb5)
![Snipaste_2024-08-19_22-25-03](https://github.com/user-attachments/assets/700ce166-538b-45d7-a620-943cee19448f)

**Comment by sMythicalBird** [comment]
这张是新图，换背景，识别错了
