### ISSUE TITLE
[Bug]: 施工废墟休息层 未找到路径

### ISSUE THREAD

**Issue by ERRORawa** [sMythicalBird/ZenlessZoneZero-Auto#206]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.3

### 系统版本

Windows 11

### bug情况描述

之前[#197](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues/197) 提过的issue，在2.3全通带业绩模式还是一样 未找到路径
用的是v2.3 CPU一键包，没有做过任何修改

### 上传截图

![WechatIMG3445](https://github.com/user-attachments/assets/0b2a61b9-b1e0-4153-bbd3-2a5e6eebcf7c)

**Comment by sMythicalBird** [comment]
> ### 请确保您已经阅读并同意以下要求
> 
> - [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
> - [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
> - [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
> - [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理
> 
> ### 项目版本
> 
> v2.3
> 
> ### 系统版本
> 
> Windows 11
> 
> ### bug情况描述
> 
> 之前[#197](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues/197) 提过的issue，在2.3全通带业绩模式还是一样 未找到路径
> 用的是v2.3 CPU一键包，没有做过任何修改
> 
> ### 上传截图
> 
> ![WechatIMG3445](https://github.com/user-attachments/assets/0b2a61b9-b1e0-4153-bbd3-2a5e6eebcf7c)

你这个肯定不是新的，第二层根本不会这么走

**Comment by ERRORawa** [comment]
脚本就是直接走到了邦布在的那个位置，后面我是暂停了脚本去拿的零号业绩再截的图，忘记说了…

**Comment by sMythicalBird** [comment]
> > > ### 请确保您已经阅读并同意以下要求
> > > 
> > > * [x]  我已阅读项目使用说明，并且按照要求更改了游戏配置
> > > * [x]  我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
> > > * [x]  我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
> > > * [x]  我已经知晓并同意，若该问题与程序无关，将不会被处理
> > > 
> > > ### 项目版本
> > > v2.3
> > > ### 系统版本
> > > Windows 11
> > > ### bug情况描述
> > > 之前[#197](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues/197) 提过的issue，在2.3全通带业绩模式还是一样 未找到路径
> > > 用的是v2.3 CPU一键包，没有做过任何修改
> > > ### 上传截图
> > > ![WechatIMG3445](https://private-user-images.githubusercontent.com/95691967/359181353-0b2a61b9-b1e0-4153-bbd3-2a5e6eebcf7c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNTIzNDIsIm5iZiI6MTcyNDE1MjA0MiwicGF0aCI6Ii85NTY5MTk2Ny8zNTkxODEzNTMtMGIyYTYxYjktYjFlMC00MTUzLWJiZDMtMmE1ZTZlZWJjZjdjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDExMDcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiYzBmY2IzYmJhNjQ0ZjgyOWJjNTg5YWJlZjllNTI1MDhmYzhiYWFhM2I0NjNjZThmY2U0ZjM2OTA4ZTgwZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Bd4oEv7S0p-JklGDWKWp3qNgO7N8G-mIGl570tjvP0)
> > 
> > 
> > 你这个肯定不是新的，第二层根本不会这么走
> 
> 脚本就是直接走到了邦布在的那个位置，后面我是暂停了脚本去拿的零号业绩再截的图，忘记说了…

一直这样还是偶发性的

**Comment by ERRORawa** [comment]
> > > > ### 请确保您已经阅读并同意以下要求
> > > > 
> > > > * [x]   我已阅读项目使用说明，并且按照要求更改了游戏配置
> > > > * [x]   我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
> > > > * [x]   我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
> > > > * [x]   我已经知晓并同意，若该问题与程序无关，将不会被处理
> > > > 
> > > > ### 项目版本
> > > > v2.3
> > > > ### 系统版本
> > > > Windows 11
> > > > ### bug情况描述
> > > > 之前[#197](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues/197) 提过的issue，在2.3全通带业绩模式还是一样 未找到路径
> > > > 用的是v2.3 CPU一键包，没有做过任何修改
> > > > ### 上传截图
> > > > ![WechatIMG3445](https://private-user-images.githubusercontent.com/95691967/359181353-0b2a61b9-b1e0-4153-bbd3-2a5e6eebcf7c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNTIzNDIsIm5iZiI6MTcyNDE1MjA0MiwicGF0aCI6Ii85NTY5MTk2Ny8zNTkxODEzNTMtMGIyYTYxYjktYjFlMC00MTUzLWJiZDMtMmE1ZTZlZWJjZjdjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDExMDcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiYzBmY2IzYmJhNjQ0ZjgyOWJjNTg5YWJlZjllNTI1MDhmYzhiYWFhM2I0NjNjZThmY2U0ZjM2OTA4ZTgwZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Bd4oEv7S0p-JklGDWKWp3qNgO7N8G-mIGl570tjvP0)
> > > 
> > > 
> > > 你这个肯定不是新的，第二层根本不会这么走
> > 
> > 
> > 脚本就是直接走到了邦布在的那个位置，后面我是暂停了脚本去拿的零号业绩再截的图，忘记说了…
> 
> 一直这样还是偶发性的

这周零号业绩已经拿到上限了，可能得等到下周再测（？
