### ISSUE TITLE
[Bug]: 休息区遇到狼叔影画事件会卡住

### ISSUE THREAD

**Issue by xya233** [sMythicalBird/ZenlessZoneZero-Auto#207]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.2 (Default)

### bug情况描述

休息区遇到狼叔影画事件会卡住

**Comment by sMythicalBird** [comment]
图呢

**Comment by xya233** [comment]
当时没保存 &nbsp;下次再遇到截一个发你



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Sugar ***@***.***&gt;
发送时间: 2024年8月20日 02:10
收件人: sMythicalBird/ZenlessZoneZero-Auto ***@***.***&gt;
抄送: xya233 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [sMythicalBird/ZenlessZoneZero-Auto] [Bug]: 休息区遇到狼叔影画事件会卡住 (Issue #207)





 
图呢
