### ISSUE TITLE
[Bug]: 旧都列车核心第一层就卡住

### ISSUE THREAD

**Issue by suguruosako** [sMythicalBird/ZenlessZoneZero-Auto#211]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.2 (Default)

### 系统版本

Windows 11

### bug情况描述

大概刷2-3把就会出现一次，只会一直往下走然后被传送带传上来

### 上传截图

![f2f533329eecc3ffe3993ab0c952eb2c](https://github.com/user-attachments/assets/68d42f5c-f9c9-4802-85fb-0473adacfa4e)

**Comment by lazydog28** [comment]
代码是最新的吗？

**Comment by suguruosako** [comment]
> 代码是最新的吗？

是的，2.3.1版

**Comment by sMythicalBird** [comment]
> > 代码是最新的吗？
> 
> 是的，2.3.1版

模型问题，向上的传送带识别错了，后面再跑个模型

**Comment by sMythicalBird** [comment]
改过了
