### ISSUE TITLE
可以加个自动释放终结技能功能吗

### ISSUE THREAD

**Issue by zidianzhimeng** [sMythicalBird/ZenlessZoneZero-Auto#218]
终结技写到yaml里终究不合理，停滞时间过长，希望能做个检测终结技是否充满。并选择固定角色释放的功能

**Comment by zidianzhimeng** [comment]
具体实现可以这样：开放一个子线程用于持续检测终结技充能到了什么状态，目前角色都是【极】释放，不排除后续其他等级。在角色战斗yaml中写入例如 key: q，循环到这一步，如果达到该角色释放终结技的等级就释放，未达到就无视

**Comment by sMythicalBird** [comment]
新版加了设计功能，自己diy吧
