### ISSUE TITLE
[Bug]:  打了一会儿自动退出，显示exit status 0xc0000005

### ISSUE THREAD

**Issue by Mrlanger668** [sMythicalBird/ZenlessZoneZero-Auto#219]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

None (Default)

### bug情况描述

GPU和CPU都这样

### 上传截图

![1724928955214](https://github.com/user-attachments/assets/d995c2a7-c9b1-4240-b551-00f37830edee)

**Comment by sMythicalBird** [comment]
电脑内存多少

**Comment by Mrlanger668** [comment]
> 电脑内存多少

32g
