### ISSUE TITLE
[Bug]: 运行开始后,正常运行几分钟后电脑黑屏.

### ISSUE THREAD

**Issue by hujianha** [sMythicalBird/ZenlessZoneZero-Auto#220]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.3.1

### 系统版本

Windows 11

### bug情况描述

使用的是cpu版本, cpu:amd3900x
下载后当天运行是正常的,隔天再试就会出现以下状况,运行后几分钟后电脑黑屏,像是死机了,只能重启电脑

### 上传截图

没有截图,运行过程是正常的,突然就黑屏,没有任何错误提示.

**Comment by sMythicalBird** [comment]
没遇到过，没报错不清楚你什么情况，电脑内存多少
