### ISSUE TITLE
[Bug]: 进入战斗后不打架干站着

### ISSUE THREAD

**Issue by XYMPHONY** [sMythicalBird/ZenlessZoneZero-Auto#226]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.4 (Default)

### 系统版本

Windows 10

### bug情况描述

程序窗口没有战斗信息，游戏内也不战斗干站着，以前版本运行正常的

### 上传截图

![image](https://github.com/user-attachments/assets/6bd99f1e-bbcb-467a-9b31-e9a0edeac10f)

**Comment by sMythicalBird** [comment]
游戏画面呢

**Comment by XYMPHONY** [comment]
![image](https://github.com/user-attachments/assets/708ce0f0-f86f-4ad7-84a3-4e8616679fdd)

**Comment by sMythicalBird** [comment]
不是说了切人键用space吗，你换哪个版本来他也不动啊

**Comment by XYMPHONY** [comment]
切人两个键来着，space和鼠标侧键，这个ui也会影响么

**Comment by XYMPHONY** [comment]
把侧键清除了又可以正常战斗了，我的问题）
