### ISSUE TITLE
[Bug]: 战斗配置选择全是黑的

### ISSUE THREAD

**Issue by hwsshly** [sMythicalBird/ZenlessZoneZero-Auto#228]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.4 (Default)

### 系统版本

Windows 10

### bug情况描述

战斗配置选择全是黑的

### 上传截图

![QQ图片20240906142103](https://github.com/user-attachments/assets/199d30c4-20f4-4cd3-b81b-d3dc9830c5dc)

**Comment by sMythicalBird** [comment]
系统主题色是什么

**Comment by khewweifeng** [comment]
W11 黑色主题也是有类似问题 ， 情况是全白 （下拉列表部分没问题）

**Comment by sMythicalBird** [comment]
因为我主题色是白的

**Comment by zidianzhimeng** [comment]
我也是全黑

**Comment by XYMPHONY** [comment]
win10 浅色主题也有这种情况，能不能单给选项卡加个背景色

**Comment by IsSmallPigPig** [comment]
因为浅色和深色主题都没适配完全，晚点再搞了

**Comment by chenmg2020** [comment]
请问大佬，现在每个角色都得自己配置战斗逻辑了吗，没有像之前一样每个角色都有默认配置了吗 @sMythicalBird

**Comment by IsSmallPigPig** [comment]
/resources/fightlogic 那里不是有吗。。

**Comment by sMythicalBird** [comment]
> 请问大佬，现在每个角色都得自己配置战斗逻辑了吗，没有像之前一样每个角色都有默认配置了吗 @sMythicalBird

不是有吗，逻辑选择不是都有一个默认逻辑吗

**Comment by chenmg2020** [comment]
> > 请问大佬，现在每个角色都得自己配置战斗逻辑了吗，没有像之前一样每个角色都有默认配置了吗 @sMythicalBird
> 
> 不是有吗，逻辑选择不是都有一个默认逻辑吗

原来如此，还以为那个默认逻辑是一个所有角色通用的战斗逻辑，哈哈哈
