### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by asdffgjkalldbd** [sMythicalBird/ZenlessZoneZero-Auto#229]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.4 (Default)

### bug情况描述

以前安装过相关的requirement,也能运行程序.
更新成2.4.0版本后发现需要安装新的requirement,遂安装了新的requirement,但是出现了错误,程序运行不了,不知道什么原因

### 上传截图

![无标题](https://github.com/user-attachments/assets/5efb9322-cef7-4ed1-bf54-6414a77d16aa)

**Comment by sMythicalBird** [comment]
为什么不运行主函数呢

**Comment by wizardt** [comment]
> 为什么不运行主函数呢

我也没找到主函数
