### ISSUE TITLE
[bug]无法识别到进入战斗状态

### ISSUE THREAD

**Issue by xlone2001** [sMythicalBird/ZenlessZoneZero-Auto#23]
python版本 3.11.0
使用requirement安装依赖
pip install --upgrade -r requirements-cuda.txt
pip install --upgrade -r requirements.txt
脚本运行没有报错
地图正常识别、移动并处理事件
进入战斗格子后，python窗口提示仍停留在当前页面：地图层数_1，但是实际已经进入战斗画面了
![image](https://github.com/user-attachments/assets/01bb2f23-ee12-4b58-be26-b706a78348c8)
只能F10暂停线程手动战斗。
角色使用的是11号，问题稳定复现
尝试继续安装cpu识别的依赖
pip install --upgrade -r requirements-cpu.txt
问题仍然复现

**Comment by sMythicalBird** [comment]
游戏是不是改键了，别自己设置按键，换回默认按键

**Comment by xlone2001** [comment]
换人绑定过第二按键到鼠标键，恢复默认后正常工作，谢谢回复。
