### ISSUE TITLE
[Bug]: 战斗时鼠标中键一直在不断选定

### ISSUE THREAD

**Issue by tasuilinghua** [sMythicalBird/ZenlessZoneZero-Auto#230]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.4 (Default)

### 系统版本

Windows 11

### bug情况描述

鼠标中键一直在不断锁定敌人，在群里问了以后，开关HDR都尝试过，偶尔锁定正常（拳击手），闪现哥基本都是一直在不断重复锁定

**Comment by zidianzhimeng** [comment]
![1](https://github.com/user-attachments/assets/9d840e9b-65cf-4164-902f-eecdbda2e240)
这个bug是因为，原代码这部分逻辑，战斗角色始终识别为【默认】，从而死循环，可以考虑像我这样修改

**Comment by sMythicalBird** [comment]
问问题先发截图，谁知道你是什么问题

**Comment by SunFrosty** [comment]
我也遇到了 战斗中抢占键鼠真截不了图  我用的间 估计就是没战斗策略文件的问题

**Comment by SunFrosty** [comment]
> ![1](https://private-user-images.githubusercontent.com/83943002/365419427-9d840e9b-65cf-4164-902f-eecdbda2e240.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MTY4NTUsIm5iZiI6MTcyNTkxNjU1NSwicGF0aCI6Ii84Mzk0MzAwMi8zNjU0MTk0MjctOWQ4NDBlOWItNjVjZi00MTY0LTkwMmYtZWVjZGJkYTJlMjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDIxMTU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlZjBlYjNjNDAxNmM4MmJkNDlmOTMzMTU2MTdmODE4MDExMjY3ZDFjZmI3MzI3NTg4Nzg3ZWM1Y2ExODRjOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZMbCjZ8RBRTr1sdbrroeWI7LHNTLn8aZIpW-wnsJrug) 这个bug是因为，原代码这部分逻辑，战斗角色始终识别为【默认】，从而死循环，可以考虑像我这样修改

我在主窗口配置里也加了队伍信息。之后好了 不知道后面这步有没有影响

**Comment by sMythicalBird** [comment]
@SunFrosty 为什么会是默认，没选角色吗

**Comment by SunFrosty** [comment]
最开始运行没看到队伍配置，更新完就没改设置

**Comment by zidianzhimeng** [comment]
> @SunFrosty 为什么会是默认，没选角色吗
其实还是角色识别的问题，有时候战斗头像的左下角会有粉色的图标，我用妮可就经常有这个问题，识别不到角色

**Comment by sMythicalBird** [comment]
> > @SunFrosty 为什么会是默认，没选角色吗
> > 其实还是角色识别的问题，有时候战斗头像的左下角会有粉色的图标，我用妮可就经常有这个问题，识别不到角色

头像被挡住了？没遇到识别失败的情况啊

**Comment by zidianzhimeng** [comment]
@SunFrosty 用最新的代码能解决这个问题
