### ISSUE TITLE
[Bug]: no Qt plugins

### ISSUE THREAD

**Issue by asdffgjkalldbd** [sMythicalBird/ZenlessZoneZero-Auto#231]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.4 (Default)

### bug情况描述

我已经安装了pyqt5
也试着在系统环境变量中加上相关路径
但报错解决不了

### 上传截图

![无标题](https://github.com/user-attachments/assets/001f78bb-7c2a-40f5-a8e0-12272096b9d7)

**Comment by asdffgjkalldbd** [comment]
![Uploading 无标111111题.jpg…]()

**Comment by sMythicalBird** [comment]
用的piside6，你装qt5有什么用

**Comment by asdffgjkalldbd** [comment]
![image](https://github.com/user-attachments/assets/a785d26a-4c5c-4851-8968-b5de68770e91)
pyside6我也装了,
一开始报错以后,我尝试自己解决bug,搜网上的解决办法是装pyqt5

**Comment by asdffgjkalldbd** [comment]
![无标题](https://github.com/user-attachments/assets/e37e052e-d487-4400-b8df-2805dda937c3)
emmmm换成pyside6还是不行,难不成还得降版本?

**Comment by asdffgjkalldbd** [comment]
![image](https://github.com/user-attachments/assets/7f5c90a0-34d3-4dd5-bb56-ab608bc3788d)
将pyside6降至6.6.2版本解决了上述问题
但是出现了新的问题,
代码运行到这一行的时候卡住了
model = InferenceSession(str(model_path), providers=Provider)
...这也太奇怪了

**Comment by asdffgjkalldbd** [comment]
![image](https://github.com/user-attachments/assets/7f5c90a0-34d3-4dd5-bb56-ab608bc3788d)
将pyside6降至6.6.2版本解决了上述问题
但是出现了新的问题,
代码运行到这一行的时候卡住了
model = InferenceSession(str(model_path), providers=Provider)
...这也太奇怪了

**Comment by sMythicalBird** [comment]
我pyside6是6.7.2，没出过问题，你是一键包还是自己装的，是不是你用的本地环境，有其他依赖版本有冲突
