### ISSUE TITLE
[Bug]: 每次都有几率卡在类似这种楼梯拐角,不会绕路也不会退出重进

### ISSUE THREAD

**Issue by fengziX** [sMythicalBird/ZenlessZoneZero-Auto#232]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.4 (Default)

### 系统版本

Windows 10

### bug情况描述

每次都有几率卡在类似这种楼梯拐角,不会绕路也不会退出重进

### 上传截图

![QQ20240908-233845](https://github.com/user-attachments/assets/192489b3-e103-4d77-8dcd-7e7d4290c29c)

**Comment by sMythicalBird** [comment]
等自己退把

**Comment by fengziX** [comment]
> 等自己退把

 有一次我记得卡了4个多小时 ...
