### ISSUE TITLE
[Bug]: 2.4版本，已requirements-dml.txt。 然后运行app.py报错

### ISSUE THREAD

**Issue by wizardt** [sMythicalBird/ZenlessZoneZero-Auto#233]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.4 (Default)

### bug情况描述

![image](https://github.com/user-attachments/assets/cf43f92e-7884-4392-b419-2e34b75c1655)
2.4版本，已运行pip install -r requirements-dml.txt，依赖环境都已更新到子文件夹py310下了。
然后运行app.py报错
```
PS G:\starrail\ZZZAUTO\ZenlessZoneZero-Auto> G:\starrail\ZZZAUTO\ZenlessZoneZero-Auto\py310\python.exe app.py
Traceback (most recent call last):
  File "G:\starrail\ZZZAUTO\ZenlessZoneZero-Auto\app.py", line 29, in <module>
    from PySide6.QtWidgets import QApplication
ModuleNotFoundError: No module named 'PySide6'
```
随后单独pip  install PySide6，都安装完毕，重新执行app.py，报错：
```
PS G:\starrail\ZZZAUTO\ZenlessZoneZero-Auto> G:\starrail\ZZZAUTO\ZenlessZoneZero-Auto\py310\python.exe app.py
Traceback (most recent call last):
  File "G:\starrail\ZZZAUTO\ZenlessZoneZero-Auto\app.py", line 30, in <module>
    from gui.main_window import MainWindow
  File "G:\starrail\ZZZAUTO\ZenlessZoneZero-Auto\gui\main_window.py", line 8, in <module>
    from qfluentwidgets import MSFluentWindow, NavigationItemPosition
ModuleNotFoundError: No module named 'qfluentwidgets'
```
随后再pip install qfluentwidgets， 提示：
`Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement qfluentwidgets (from versions: none)
ERROR: No matching distribution found for qfluentwidgets`

**Comment by SunFrosty** [comment]
可能是qt和pyside版本冲突？先卸载这些包，然后重新安装requirment的里的PySide6-Fluent-Widgets试试

**Comment by sMythicalBird** [comment]
requirements-dml.txt少了PySide6-Fluent-Widgets依赖，现在没用那个文件，就没更新，不想用一键包为什么不直接用conda呢

**Comment by wizardt** [comment]
> requirements-dml.txt少了PySide6-Fluent-Widgets依赖，现在没用那个文件，就没更新，不想用一键包为什么不直接用conda呢
大佬好。不是不想用一键包。是想用GPU，又想用2.4...CUDA那些环境都是OK的，最后使用一键包补全了所有依赖，运行app.py出现了gui，等于还是CPU版？

**Comment by wizardt** [comment]
感谢回复，后来这么干的：↑

> 可能是qt和pyside版本冲突？先卸载这些包，然后重新安装requirment的里的PySide6-Fluent-Widgets试试

**Comment by sMythicalBird** [comment]
电脑要是环境多，那为什么不直接conda统一管理呢

**Comment by wizardt** [comment]
> requirements-dml.txt少了PySide6-Fluent-Widgets依赖，现在没用那个文件，就没更新，不想用一键包为什么不直接用conda呢

按照大佬的指示使用了conda，在py310环境下，pip了PySide6-Fluent-Widgets，运行仍然提示：
ZenlessZoneZero-Auto\app.py", line 29, in <module>
    from PySide6.QtWidgets import QApplication
ModuleNotFoundError: No module named 'PySide6'

![image](https://github.com/user-attachments/assets/420821f7-aebc-40cf-a652-85dc7ec35222)
