### ISSUE TITLE
[建议]: 队伍最终人员排序因入队先后导致不一样（之前漏掉了标题补上）

### ISSUE THREAD

**Issue by Leapiny** [sMythicalBird/ZenlessZoneZero-Auto#234]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.4 (Default)

### 系统版本

Windows 11

### bug情况描述

首先感谢ZenlessZoneZero-Auto开发团队，给我的游戏体验带来了非常重大提升。我配置的是打核心层，有一点小问题不知道是不是我使用的不对。
1、角色顺序可能变化，例如我设置 艾莲、青衣、苍角。 如果首先找到青衣，再找到苍角时就会把苍角插入到艾莲与青衣中间。这样导致苍角技能后切不到艾莲。
2、偶尔遇到非艾莲（例如苍角）放大招的情况。但明明大招只有艾莲的战斗脚本中配置了，不知道什么原因。
3、希望能有办法记录更多日志到文件，主要目的是想通过日志确认一下一共跑了多少次，每次是完美跑通，还是由于超时、死角色、卡死等原因重开的。

**Comment by sMythicalBird** [comment]
写那么复杂也没人看，而且写那些东西要花时间测试的，平时挺忙的没空搞那么细

**Comment by sMythicalBird** [comment]
入队顺序不影响
