### ISSUE TITLE
空洞脚本进入战斗模式不会退出

### ISSUE THREAD

**Issue by 2375399351** [sMythicalBird/ZenlessZoneZero-Auto#236]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.4 (Default)

### 系统版本

Windows 11

### bug情况描述

结束空洞一层战斗后，脚本还是提示进入战斗模式不会退出

### 上传截图

![D3CF20EC-FE84-449A-A112-AE66A0201227](https://github.com/user-attachments/assets/f13a719c-abac-4eea-b0a9-c05cd75936eb)
![035CF966-48C6-4266-971D-E119E3C4C520](https://github.com/user-attachments/assets/a2823229-f726-40af-908a-7d0a7ad90310)

**Comment by zidianzhimeng** [comment]
还有其他特征吗，如果是键盘一直按c，我大概知道是什么问题了

**Comment by 2375399351** [comment]
> 还有其他特征吗，如果是键盘一直按c，我大概知道是什么问题了

w也按

**Comment by zidianzhimeng** [comment]
https://github.com/zidianzhimeng/ZenlessZoneZero-Auto.git

**Comment by sMythicalBird** [comment]
> 还有其他特征吗，如果是键盘一直按c，我大概知道是什么问题了

为什么会按c，没用过这个键啊
