### ISSUE TITLE
怎么办

### ISSUE THREAD

**Issue by hwsshly** [sMythicalBird/ZenlessZoneZero-Auto#238]
![WPCJLV)R(4PY%DTGF}J(5SL](https://github.com/user-attachments/assets/c8b4e59a-788d-44fd-8a6d-7d115082feab)
![WPCJLV)R(4PY%DTGF}J(5SL](https://github.com/user-attachments/assets/c8b4e59a-788d-44fd-8a6d-7d115082feab)
![bfde4784f401cc45513ba1352aa925f5](https://github.com/user-attachments/assets/ea338632-498f-445a-b971-eaceed9bf9b5)
![bfde4784f401cc45513ba1352aa925f5](https://github.com/user-attachments/assets/ea338632-498f-445a-b971-eaceed9bf9b5)
没搞懂删了这个
![9 @KW$3OC5$PF%G_3RH%~GQ](https://github.com/user-attachments/assets/5553c31f-f10b-43e3-a8d9-51c66093989c)
![9 @KW$3OC5$PF%G_3RH%~GQ](https://github.com/user-attachments/assets/5553c31f-f10b-43e3-a8d9-51c66093989c)
之后2.2 2.3 2.31 2.40都说缺paddle.base怎么办

**Comment by sMythicalBird** [comment]
你这是提供的release版吗，提供的是cpu版的，怎么会有cuda的报错
