### ISSUE TITLE
components_level.onnx 缺失

### ISSUE THREAD

**Issue by Wangzifu98** [sMythicalBird/ZenlessZoneZero-Auto#24]
![image](https://github.com/user-attachments/assets/31863d25-0e5b-4aac-99e0-e1b4a6dfa7af)
components_level.onnx 缺失

**Comment by sMythicalBird** [comment]
你用的那个分支，这个模型是现在开发版本用的，旧版的master分支没这个，开发版本还没公布不要用

**Comment by Wangzifu98** [comment]
> 你用的那个分支，这个模型是现在开发版本用的，旧版的master分支没这个，开发版本还没公布不要用

master这个分支现在不太好用 就想用dev的

**Comment by sMythicalBird** [comment]
> > 你用的那个分支，这个模型是现在开发版本用的，旧版的master分支没这个，开发版本还没公布不要用
> 
> master这个分支现在不太好用 就想用dev的

叛逆期到了是吧，开发版本遇到问题自己看着办，没问题还能叫开发版吗

**Comment by Wodlie** [comment]
[现在有了](https://zzz.caiyun.fun/components_level.onnx)

**Comment by Wangzifu98** [comment]
> > > 你用的那个分支，这个模型是现在开发版本用的，旧版的master分支没这个，开发版本还没公布不要用
> 
> > 
> 
> > master这个分支现在不太好用 就想用dev的
> 
> 
> 
> 叛逆期到了是吧，开发版本遇到问题自己看着办，没问题还能叫开发版吗

是自己解决呀

**Comment by sMythicalBird** [comment]
> > > > 你用的那个分支，这个模型是现在开发版本用的，旧版的master分支没这个，开发版本还没公布不要用
> > 
> > 
> > > 
> > 
> > 
> > > master这个分支现在不太好用 就想用dev的
> > 
> > 
> > 叛逆期到了是吧，开发版本遇到问题自己看着办，没问题还能叫开发版吗
> 
> 是自己解决呀

你这dev用的也不是最新的呀，新的有这个模型
