### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by deksasi** [sMythicalBird/ZenlessZoneZero-Auto#240]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.4 (Default)

### bug情况描述

使用文档里提供的压缩包时，解压的瞬间，中了感染型病毒

### 上传截图

![3dff788bcb117e49320f3fde136c1f6c](https://github.com/user-attachments/assets/05905532-ee78-4174-95c6-0a85e92f8385)

![aa5c1c866ced44d34ca8e76ea27fd922](https://github.com/user-attachments/assets/1e32f780-89c3-4f66-a319-02c97599dc6c)

**Comment by sMythicalBird** [comment]
是在github下载的吗，不存在病毒，文件目录截下图，如果是正常途径下载的还出问题就把杀毒软件关了

**Comment by deksasi** [comment]
好的解决了，压缩前扫了一遍这次没有问题
