### ISSUE TITLE
[Bug]: 战斗只能极限支援，最后下A不死，去到商店和选择格子，就不会动了

### ISSUE THREAD

**Issue by yeyanghao6** [sMythicalBird/ZenlessZoneZero-Auto#241]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.4 (Default)

### 系统版本

Windows 10

### bug情况描述

战斗只能极限支援，最后下A不死，去到商店和选择格子，就不会动了

### 上传截图

https://github.com/user-attachments/assets/18edd5c3-c961-4ab4-abbd-01bae289efe6

https://github.com/user-attachments/assets/b100e4c9-766d-4cfc-8adf-9360fb906ac7

![1](https://github.com/user-attachments/assets/b68bfa41-2a65-4e40-8c64-1976c34038a6)

**Comment by sMythicalBird** [comment]
发图片为什么不发截图，你看看你切人用的是不是空格，字体是不是细体，为什么不看游戏配置要求

**Comment by AYkimchi2000** [comment]
是啊...配置要求不看就直接来issue挺烦人的

**Comment by yeyanghao6** [comment]
我原始切人空格和C，然后改了细字体 还是商店买不动

**Comment by yeyanghao6** [comment]
[
![Uploading 3.png…]()
](url)

**Comment by yeyanghao6** [comment]
![Uploading 3.png…]()
