### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by arestww** [sMythicalBird/ZenlessZoneZero-Auto#242]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.4 (Default)

### 系统版本

Windows 10

### bug情况描述

卡住了 沒有回應

### 上传截图

![image](https://github.com/user-attachments/assets/b7999833-c418-43a0-82d9-3d51968baf4f)

**Comment by arestww** [comment]
![image](https://github.com/user-attachments/assets/5fc30442-ab69-4d41-a7f9-3e2d1f0907c2)

**Comment by sMythicalBird** [comment]
运行程序后别乱动，要乱动先f12终止运行在点别的

**Comment by arestww** [comment]
![image](https://github.com/user-attachments/assets/52247019-2258-4582-a8f7-c46deeee4c92)
就是開啟然後他就直接卡住了 也沒動 大神求解

**Comment by louisdwu** [comment]
5500U小主机同样卡死了

**Comment by sMythicalBird** [comment]
@louisdwu 你开启后就别动了啊，不是写过吗，你要再动鼠标就f12先退出当前进程，算了下版本把线程拆出来把
