### ISSUE TITLE
[Bug]: 跪求，我已经整了一个月了，身上丁尼还没菲林多，实在没办法

### ISSUE THREAD

**Issue by yeyanghao6** [sMythicalBird/ZenlessZoneZero-Auto#243]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.4 (Default)

### 系统版本

Windows 10

### bug情况描述

我看过所有作者的视频，也在群里问了无数次。没人能帮我解决，无奈只能来这里求助，困扰了我一个月。我是管理员打开，字体细，1920*1080窗口，切人空格，然后配置如下，他战斗就不动。商店也不动，敏辉可以选。我V：514555341，希望有好心人帮帮我

### 上传截图

![微信截图_20240924204258](https://github.com/user-attachments/assets/eebf2f78-76b3-462b-9048-46206b6ed16a)
![微信截图_20240924204342](https://github.com/user-attachments/assets/ca095d19-dcf9-4130-990a-ef52905f0bd6)
![微信截图_20240924204415](https://github.com/user-attachments/assets/a0e9cbae-ff18-46e6-b855-780de6939f31)
![微信截图_20240924204425](https://github.com/user-attachments/assets/cde26cce-0b2c-4035-9caa-de614607c16a)
![微信截图_20240924204438](https://github.com/user-attachments/assets/ec7226ca-7128-47f7-bb90-c26dd822a380)
![微信截图_20240924204451](https://github.com/user-attachments/assets/0ca0e2aa-b19d-4c13-af31-9c794c57c007)

**Comment by Whisper85** [comment]
游戏窗口大小设置为 1280x720 窗口，帧数限制为 60 帧，用之前还是要翻一下文档……

**Comment by sMythicalBird** [comment]
游戏配置写的很清楚，界面切人键改成space，为什么不试试看呢

**Comment by yeyanghao6** [comment]
> 游戏配置写的很清楚，界面切人键改成space，为什么不试试看呢

我不就是space切换下一名角色吗

**Comment by Etelero67** [comment]
> > 游戏配置写的很清楚，界面切人键改成space，为什么不试试看呢
> 
> 我不就是space切换下一名角色吗

你space是切换上一名角色, 游戏默认是切换下一名角色

**Comment by yeyanghao6** [comment]
> > > 游戏配置写的很清楚，界面切人键改成space，为什么不试试看呢
> > 
> > 
> > 我不就是space切换下一名角色吗
> 
> 你space是切换上一名角色, 游戏默认是切换下一名角色

谢谢你 现在能正常运行了，但是遇到战斗的时候他不会平A 只会黄光触发space切人追击，远程怪A我他就站那里不动了，你有遇到吗？

**Comment by Etelero67** [comment]
> > > > 游戏配置写的很清楚，界面切人键改成space，为什么不试试看呢
> > > 
> > > 
> > > 我不就是space切换下一名角色吗
> > 
> > 
> > 你space是切换上一名角色, 游戏默认是切换下一名角色
> 
> 谢谢你 现在能正常运行了，但是遇到战斗的时候他不会平A 只会黄光触发space切人追击，远程怪A我他就站那里不动了，你有遇到吗？

战斗配置选战斗逻辑1, 别选默认逻辑.
