### ISSUE TITLE
[Bug]: 页面更新后无法进入下一层

### ISSUE THREAD

**Issue by yamleric** [sMythicalBird/ZenlessZoneZero-Auto#244]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.4 (Default)

### bug情况描述

新增「守门人界面」「商店紫色进入界面」，脚本无法识别两个界面。且目前空洞增加了模糊效果，路径识别总是失败，我法正常领取业绩。

### 上传截图

![mmexport1727273204136](https://github.com/user-attachments/assets/bccea5a1-c942-4369-9f17-da460a94b575)
![Uploading mmexport1727273071719.jpg…]()

**Comment by wxdlpxt** [comment]
坐等更新

**Comment by sMythicalBird** [comment]
晚上修

**Comment by sdxwang** [comment]
> 晚上修

目前修复的版本发现商店那个标签会反复进入，建议加下判断
![1727572254353](https://github.com/user-attachments/assets/61b6e91f-b477-4ba9-b9b1-90ec16745d97)

**Comment by sMythicalBird** [comment]
@sdxwang 什么问题截图，我测试正常

**Comment by sMythicalBird** [comment]
> > 晚上修
> 
> 目前修复的版本发现商店那个标签会反复进入，建议加下判断 ![1727572254353](https://private-user-images.githubusercontent.com/59275370/371814989-61b6e91f-b477-4ba9-b9b1-90ec16745d97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1NzM1NDcsIm5iZiI6MTcyNzU3MzI0NywicGF0aCI6Ii81OTI3NTM3MC8zNzE4MTQ5ODktNjFiNmU5MWYtYjQ3Ny00YmE5LWI5YjEtOTBlYzE2NzQ1ZDk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDAxMjcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmZjBlODNiMGJkMmVjOGRmOTA3NWE0ZjNjNjYzMjkwMTk3YTE1YzdlMTM2YjgxZTFmNTk0ZGZiYzA0NDkyNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vqOyEPvj4-se57LE9wViZnLqGYZCuIeZiIJklaxxohs)

我知道问题了

**Comment by sMythicalBird** [comment]
@sdxwang 现在应该没什么问题了，你试试

**Comment by lldql** [comment]
https://github.com/user-attachments/assets/5070115e-999f-4b2c-8a4d-e102cfec62e0

https://github.com/user-attachments/assets/16e369b2-2354-489c-973f-5f5bdcdfc6a2

1.找不到路径
2.原地重复
2024.9.29  10:13  这个时间拍摄

**Comment by sMythicalBird** [comment]
@lldql 你这是更新后的吗

**Comment by C1kir** [comment]
请问怎么更新啊

**Comment by yamleric** [comment]
希望赶紧打包2.4.1

**Comment by lldql** [comment]
@sMythicalBird 是的

**Comment by lldql** [comment]
> @lldql 你这是更新后的吗

no

**Comment by lldql** [comment]
https://github.com/user-attachments/assets/538978d5-9477-428d-ad5a-571956ea6996

我删掉重新安装后还是有这个问题，不过路径那个倒是能找见了，就是不如以前流畅

**Comment by sMythicalBird** [comment]
@lldql 你重新安装没更新吗

**Comment by Samtsirhc** [comment]
![image](https://github.com/user-attachments/assets/b1c5d435-0d12-4b0c-a937-de4f1ca6c726)
这个界面，商店会反复进入退出，一直卡在这里循环，版本2.4.0，任意商店都会这样

**Comment by kisakuya** [comment]
和上面一样的问题，「守门人界面」「商店紫色进入界面」，脚本无法识别两个界面。反复进入退出，一直卡在这里循环，版本2.4.0，刚刚下载的
