### ISSUE TITLE
[Bug]: 2.4版本无法启动 Qt's default DPI awareness context ....

### ISSUE THREAD

**Issue by pyf1835** [sMythicalBird/ZenlessZoneZero-Auto#245]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.4 (Default)

### bug情况描述

使用的是[2.4.0 CPU一键包]。无法正常启动
提示
Qt's default DPI awareness context is DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2. If you know what you are doing, you can overwrite this default using qt.conf (https://doc.qt.io/qt-6/highdpi.html#configuring-windows).

### 上传截图

![QQ20240929-192530](https://github.com/user-attachments/assets/96ef2f65-6434-4f53-ac31-3ed3522c1978)

**Comment by RuckerChen** [comment]
![image](https://github.com/user-attachments/assets/5ee401d9-9f6f-4008-98d7-03a27e175860)
我卡這一直沒動

**Comment by pyf1835** [comment]
> ![图像](https://private-user-images.githubusercontent.com/64086374/371854381-5ee401d9-9f6f-4008-98d7-03a27e175860.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MTM2MzIsIm5iZiI6MTcyNzYxMzMzMiwicGF0aCI6Ii82NDA4NjM3NC8zNzE4NTQzODEtNWVlNDAxZDktOWY2Zi00MDA4LTk4ZDctMDNhMjdlMTc1ODYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDEyMzUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0ODJiMGIzYzQ1MmI5OGFlMTM2N2RkYmJhNmRkZGE0ZWNlOGE1ZjEwZDI5ODA3NTRkNTlkZTJjYWU2NzBlM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4he9BU1WYap_5pLYZDB3Ttqoh_d4YSuWNhdpd_GeQ40)我卡這一直沒動

我本想说，我连这一步都没出。重新开了一次。弹出一个新的UI界面。好像好使了
