### ISSUE TITLE
[Bug]: 不识别战斗，不战斗

### ISSUE THREAD

**Issue by zlb216** [sMythicalBird/ZenlessZoneZero-Auto#249]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.4 (Default)

### 系统版本

Windows 10

### bug情况描述

[Bug]: 不识别战斗，不战斗

### 上传截图

![图片1](https://github.com/user-attachments/assets/a80c3f8e-fc03-4e93-b900-2905e705f52c)

**Comment by sMythicalBird** [comment]
把图截全

**Comment by zlb216** [comment]
![QQ截图20241001182100](https://github.com/user-attachments/assets/25514f69-d801-410c-ae29-31a39a451671)
进入战斗后没反应

**Comment by sMythicalBird** [comment]
你看你画面切人是space吗，按要求设置

**Comment by zlb216** [comment]
![QQ截图20241001182413](https://github.com/user-attachments/assets/ff1b5edf-1b97-4d72-a502-55e743ea6bc5)
2.0就开始用了，设置也是按要求弄的。

**Comment by sMythicalBird** [comment]
你看你第三条对吗

**Comment by zlb216** [comment]
![Uploading QQ截图20241001183001.png…]()

**Comment by zlb216** [comment]
![QQ截图20241001183001](https://github.com/user-attachments/assets/073fcc4e-ad23-4c0f-8464-a933f738c71c)
![QQ截图20241001183011](https://github.com/user-attachments/assets/2d846219-270c-4bff-8778-f26215728c3b)
![QQ截图20241001183022](https://github.com/user-attachments/assets/4fba0f72-76ad-4e25-9803-a4e5ba4002c1)
![QQ截图20241001183033](https://github.com/user-attachments/assets/30ca44fc-dcb3-4044-a67d-f52871a0b08e)

**Comment by sMythicalBird** [comment]
![image](https://github.com/user-attachments/assets/aef56964-affa-477f-9c2e-a6b45cb21157)
嘴怎么这么硬啊

**Comment by zlb216** [comment]
懂了，昨天设的额外按键，空格键没动，恢复默认了，重新下了2.4，可以了。
