### ISSUE TITLE
[Bug]: 已经结束战斗了，仍在战斗模式

### ISSUE THREAD

**Issue by Jarvis-hjr** [sMythicalBird/ZenlessZoneZero-Auto#250]
### 请确保您已经阅读并同意以下要求

- [X] 我已阅读项目使用说明，并且按照要求更改了游戏配置
- [X] 我已经搜索过已有的[issue](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues)，确认当前问题没有被提出过
- [X] 我已经知晓并同意，若由于个人未按要求配置导致的问题，将不会被处理
- [X] 我已经知晓并同意，若该问题与程序无关，将不会被处理

### 项目版本

v2.4 (Default)

### 系统版本

Windows 10

### bug情况描述

已经结束战斗了，仍在战斗模式，不会进入

### 上传截图

![微信截图_20241001123552](https://github.com/user-attachments/assets/f183ed98-c863-4796-b160-7dbbed65df0b)

**Comment by sMythicalBird** [comment]
是2.4.1吗，这个问题是之前一个pr引起的，已经回滚了

**Comment by Jarvis-hjr** [comment]
解决了，谢谢
