### ISSUE TITLE
远程主机强迫关闭了一个现有的连接

### ISSUE THREAD

**Issue by lbls741** [sMythicalBird/ZenlessZoneZero-Auto#27]
通过直接下载源代码压缩包的方式运行了07,17,19:00左右发布的新版本
发现文件下载链接发生了更改（https://[file.caiyun.fun/download/zzz/filelist.txt](https://file.caiyun.fun/download/zzz/filelist.txt)改为了https://[zzz.caiyun.fun/filelist.txt](https://zzz.caiyun.fun/filelist.txt)）
但网络连接状况似乎并未得到改善，且概率不会出现“文件下载失败”的报错
win11pro版的运行[日志.log](https://github.com/user-attachments/files/16265451/default.log)

**Comment by sMythicalBird** [comment]
没钱买服务器，带宽不行，算了，我去看看买一个

**Comment by lbls741** [comment]
也许可以把这一条加到README的常见问题那一栏
能用上这个工具的人，只要告知一下文件路径，应该就能自行解决了

**Comment by lazydog28** [comment]
已经付费购买了123云盘的直链下载服务作为备用下载源
