### ISSUE TITLE
[功能请求] 改用模拟手柄

### ISSUE THREAD

**Issue by LINKlang** [sMythicalBird/ZenlessZoneZero-Auto#3]
模拟手柄输入，解放键鼠，这样绝区零在后台也可以接收输入了

**Comment by sMythicalBird** [comment]
模拟手柄比较麻烦，暂时先实现自动化，后续优化的时候再考虑

**Comment by LINKlang** [comment]
> 模拟手柄比较麻烦，暂时先实现自动化，后续优化的时候再考虑

不懂就问，目前的开发侧重点是在？

**Comment by yinghaodang** [comment]
靠OCR的，即便输入改成了手柄，你也得老老实实把绝区零的窗口摆在最前面。除非用作者提供的那个后台运行的方式。
