### ISSUE TITLE
会一直卡在这个界面

### ISSUE THREAD

**Issue by IPromiseU513** [sMythicalBird/ZenlessZoneZero-Auto#30]
![Uploading 001.png…]()

**Comment by dawei233** [comment]
游戏设置说明(必须)
设置->输入->棋盘镜头移动速度->1

设置->画面->显示模式->1280*720窗口

设置->键鼠设置->角色切换下一位->Space

图片看不了不过按照这个设置以后估计就没事了

**Comment by lazydog28** [comment]
截图没上传
