### ISSUE TITLE
事件bug

### ISSUE THREAD

**Issue by Lioncon** [sMythicalBird/ZenlessZoneZero-Auto#32]
![Uploading QQ20240718-111813.png…]()

**Comment by Lioncon** [comment]
![Uploading QQ20240718-111813.png…]()

**Comment by lazydog28** [comment]
#26 

在这下面上传截图

**Comment by Lioncon** [comment]
![Uploading QQ20240718-111813.png…]()

**Comment by Lioncon** [comment]
传不上捏

**Comment by Lioncon** [comment]
![QQ20240718-111813](https://github.com/user-attachments/assets/f4a50299-f66f-4f32-b4d2-1dcc7981a264)

**Comment by Lioncon** [comment]
施工废墟

**Comment by Lioncon** [comment]
有人传了喔
