### ISSUE TITLE
领取业绩后，窗口偏移导致无法识别到自身位置

### ISSUE THREAD

**Issue by zmwz233** [sMythicalBird/ZenlessZoneZero-Auto#33]
![2](https://github.com/user-attachments/assets/01cfdeea-cd58-495f-82f8-36f0f5eddbbf)

**Comment by zmwz233** [comment]
![1](https://github.com/user-attachments/assets/718e8949-cf05-4ff4-a36c-1e677be06ac8)
进入第二层也会直接自动向右上滑动屏幕，导致识别不到自己

**Comment by lazydog28** [comment]
![image](https://github.com/user-attachments/assets/eba4d0a7-2631-4ef5-aaef-1c894a8f518d)
