### ISSUE TITLE
Trackback Fail

### ISSUE THREAD

**Issue by d170798091** [sMythicalBird/ZenlessZoneZero-Auto#35]
![image](https://github.com/user-attachments/assets/7a6e31d7-8616-47a0-8558-30ee368b1f9f)

![image](https://github.com/user-attachments/assets/a9d8ce54-8055-4478-8d9a-66b6a5b17eef)

不確定是哪個方向有問題?

是跟遊戲只抓取國區版有關嗎?

**Comment by lazydog28** [comment]
代码问题，已经修复
