### ISSUE TITLE
[功能请求]战斗部分能否参考其它项目闪红光或黄光时闪避？

### ISSUE THREAD

**Issue by xlone2001** [sMythicalBird/ZenlessZoneZero-Auto#39]
我目前0+0的艾莲，40级人物+40级的A级武器+鲨鱼布+所有技能7级，无法通关旧都列车前线。最终boss红光攻击时总是顶着攻击，掉血很快，只能刷零号业绩。
需要多少强度才能过，有参考吗？如果可以识别红光和黄光攻击，后续的地图通关难度也会降低。
红光闪避可参考项目：
https://github.com/DoctorReid/ZenlessZoneZero-OneDragon(实测正常工作)
https://github.com/yiyangc18/Zzz_PerfectAssist（未实际测试）
此外目前生命回复、金币和减压三选一时选的是金币，而实际走到商店格子并不会买东西。是否在目前阶段优先选生命回复来增加续航，等后续能自动买鸣徽后再优先选金币？

**Comment by sMythicalBird** [comment]
战斗后面用空再说，战斗逻辑函数是独立的，你可以自己先改个战斗逻辑凑合着用
