### ISSUE TITLE
Script cannot run through discarded blessings

### ISSUE THREAD

**Issue by ParasiteEve** [sMythicalBird/ZenlessZoneZero-Auto#40]
![image](https://github.com/user-attachments/assets/31702dc7-a514-4161-836d-e9e1f6bc1b9e)

Please see image attached, script always get stuck if I face the screen where I discard blessings

**Comment by ParasiteEve** [comment]
![image](https://github.com/user-attachments/assets/5695a95e-593c-4b2c-82cb-2fd4ef6e289b)

**Comment by lazydog28** [comment]
已修复
4b6b378069c2487717e90caced30388bb8ddfe30
