### ISSUE TITLE
本人为新手小白，在云盘下载的启动器，遇到的一些问题

### ISSUE THREAD

**Issue by pyf1835** [sMythicalBird/ZenlessZoneZero-Auto#42]
云盘下载启动器，正常启动。选择了1，安装依赖等。
看到下载了很多依赖包。大概几个G。不知道这些包安装到了哪里，安装后是否会自动删除掉安装包？以及后续不用的时候，如何删除这些下载的东西，释放占用的空间。

感谢解答

**Comment by lazydog28** [comment]
安装到项目目录下的`py310`目录下

安装完成以后不会删除缓存

pip安装的缓存正常是在`c:\users\${username}\appdata\local\pip\cache`
