### ISSUE TITLE
Zone 3 and up.

### ISSUE THREAD

**Issue by ParasiteEve** [sMythicalBird/ZenlessZoneZero-Auto#46]
![image](https://github.com/user-attachments/assets/c5178053-8710-4d86-8a49-07495bb4a2d8)
Can you enable Zone 3? Thank you so much.

**Comment by sMythicalBird** [comment]
第三关我还没解锁，解锁之后再做适配，还有目前脚本只支持简中字体，如果是其他语言暂时未作适配

**Comment by ParasiteEve** [comment]
Yeah, I've been using it in Chinese, thank you!
