### ISSUE TITLE
支持emulator

### ISSUE THREAD

**Issue by JerryLingjieMei** [sMythicalBird/ZenlessZoneZero-Auto#5]
类似https://github.com/LmeSzinc/StarRailCopilot 的自动脚本可以使用android emulator 进行更快速的截屏和反馈， 同时也不会占用电脑的鼠标， 可以参考一下类似的支持。

**Comment by sMythicalBird** [comment]
等项目开发完，后期优化的时候可以考虑做一下

**Comment by Kol96** [comment]
win32gui.PostMessage 可以直接给游戏窗口发送按键 这样鼠标不在游戏窗口内就不影响

**Comment by sMythicalBird** [comment]
> win32gui.PostMessage 可以直接给游戏窗口发送按键 这样鼠标不在游戏窗口内就不影响

不支持给游戏窗口发送键鼠指令

**Comment by lazydog28** [comment]
> win32gui.PostMessage 可以直接给游戏窗口发送按键 这样鼠标不在游戏窗口内就不影响

这个方案之前试过了，但是游戏根本不处理这种事件。只有 directinput 才会进行处理

**Comment by snowly233** [comment]
> 类似https://github.com/LmeSzinc/StarRailCopilot 的自动脚本可以使用android emulator 进行更快速的截屏和反馈， 同时也不会占用电脑的鼠标， 可以参考一下类似的支持。

完犊子了，alas，src上瘾了，zzz也离不开脚本了
