### ISSUE TITLE
发现更快更高效的刷丁尼方法

### ISSUE THREAD

**Issue by LYIFIDI** [sMythicalBird/ZenlessZoneZero-Auto#51]
旧都列车前线，只要打完第1层boos
然后退出 就能获得400丁尼
只要不拿业绩就没有上限 
实测一分钟一把
400*60*24=576000
一天可得57万丁尼
![111](https://github.com/user-attachments/assets/0b8ba58b-80b3-492c-80ef-b7b801f7461f)

**Comment by sMythicalBird** [comment]
确定？零号空洞奖励不是有次数上限吗
