### ISSUE TITLE
Zone 3-1 Final Area Error

### ISSUE THREAD

**Issue by ParasiteEve** [sMythicalBird/ZenlessZoneZero-Auto#52]
![image](https://github.com/user-attachments/assets/5a340f94-e01f-450b-a085-b6adcb7223ef)
Since map is not straight and character has move a bit to the left, the character is stuck attacking the wall

**Comment by ParasiteEve** [comment]
![image](https://github.com/user-attachments/assets/fc5c46ac-bc97-41ac-89a8-11f0b71eef8d)

**Comment by sMythicalBird** [comment]
战斗这个版本还未做适配
