### ISSUE TITLE
【功能请求】最大战斗时间区分boss关与小怪关

### ISSUE THREAD

**Issue by MomentDerek** [sMythicalBird/ZenlessZoneZero-Auto#53]
最大战斗时间主要是用于打不过和转场战斗（有两拨怪，目前脚本无法处理，所以需要靠超时跳过）的场景

但是转场战斗一般20s就打完了，剩下的两分钟都在原地平a，等超时

boss关一般需要顶着100多s，所以boss关和小怪关是否可以分开？

大概看了看源码，有点蒙蒙的，不大敢提pr，是不是在下面这个地方往StatusInfo里丢一个boss关标识，就能识别到当前关卡是否为boss关？
```python
@task.page(name="目标位置", target_texts=["关键进展", "^确认继续$"])
def action(positions: Dict[str, Position]):
    pos = positions.get("^确认继续$")
    info.currentStage = 1
    control.click(pos.x, pos.y)
    # 进入战斗
```

**Comment by sMythicalBird** [comment]
> 最大战斗时间主要是用于打不过和转场战斗（有两拨怪，目前脚本无法处理，所以需要靠超时跳过）的场景
> 
> 但是转场战斗一般20s就打完了，剩下的两分钟都在原地平a，等超时
> 
> boss关一般需要顶着100多s，所以boss关和小怪关是否可以分开？
> 
> 大概看了看源码，有点蒙蒙的，不大敢提pr，是不是在下面这个地方往StatusInfo里丢一个boss关标识，就能识别到当前关卡是否为boss关？
> 
> ```python
> @task.page(name="目标位置", target_texts=["关键进展", "^确认继续$"])
> def action(positions: Dict[str, Position]):
>     pos = positions.get("^确认继续$")
>     info.currentStage = 1
>     control.click(pos.x, pos.y)
>     # 进入战斗
> ```

可以的，这个确实再考虑，这个版本就在考虑怎么做战斗优化
