### ISSUE TITLE
Screen always stuck here for hours when doing Zone 1-2

### ISSUE THREAD

**Issue by ParasiteEve** [sMythicalBird/ZenlessZoneZero-Auto#55]
![image](https://github.com/user-attachments/assets/853840d3-bd26-4293-82c8-3207a9a9cc8e)

**Comment by lazydog28** [comment]
![image](https://github.com/user-attachments/assets/446fe3fb-0967-4820-975c-9462f368f97a)


设置->输入->棋盘镜头移动速度->1
