### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by nyano** [sMythicalBird/ZenlessZoneZero-Auto#58]
您好大佬：
1.我看到了关闭议题中，暂时不做战斗部分，不过因为没有闪避能力，大概率目前只能在低等级类目下循环，打核心等部分大概率便当
2.建议优先能够识别添加代理人的格子走，一个人打实在太难太累了【特别是在问题1的情况下】=》扩展可以识别隐藏格子，但这不重要
3.建议能够识别并打开左上角走格子加速模式，有些长废话真的走的累
4.5秒一次的识别走格子效率感觉还是略慢点（特别是3长废话难受，必须手动）
5.F11暂停了好像还是有在移动鼠标
6.如关闭议题中，部分战斗卡墙情况（应该是训练问题，这不是问题）
7.在启动和F10恢复时，建议添加一个自动游戏前置的功能（老是忘）

总结：目前无法实现全自动化我认为主要是1是不能优先获得其他代理人（当然低等级的也够了），2是战斗不能闪避，造成失败

以下为DLC1内容：
1.我等了半天，然后才发现启动后自动暂停，并且无法F10恢复，因为代码里：
`if __name__ == "__main__":
    task.pause()
`
2.由于对比main.py，缺失path环境变量部分，造成错误，无法继续
3.在对话交付部分，似乎是由于分辨率问题，无法正确点到对话项，但是其他按钮部分均正常
在money.py中，似乎这个是固定坐标，未做不同坐标识别，是否可以改为直接OCR识别？
`control.click(1020, 440)`

**Comment by lazydog28** [comment]
战斗部分代码在`fight.py`，可以自行添加或修改
https://github.com/sMythicalBird/ZenlessZoneZero-Auto/blob/master/handle/fight.py

代理人格子优先级暂不考虑提高，重新训练模型很麻烦

走格子加速并不会快很多，并且增加了不稳定性，等以后脚本稳定以后再考虑

走格子效率取决于你的电脑性能，并没有固定成5秒识别一次

卡墙是因为战斗地图中没法寻路，暂时没想出什么好办法，如果你有什么好的办法，可以提出

自动游戏前置的功能可以考虑添加

**Comment by lazydog28** [comment]
自动游戏前置的功能去测试了一下，脚本设置游戏前置需要附加线程到游戏，这个操作风险很大，可能会导致判定为修改数据。所以暂不考虑

**Comment by sMythicalBird** [comment]
> 您好大佬： 1.我看到了关闭议题中，暂时不做战斗部分，不过因为没有闪避能力，大概率目前只能在低等级类目下循环，打核心等部分大概率便当 2.建议优先能够识别添加代理人的格子走，一个人打实在太难太累了【特别是在问题1的情况下】=》扩展可以识别隐藏格子，但这不重要 3.建议能够识别并打开左上角走格子加速模式，有些长废话真的走的累 4.5秒一次的识别走格子效率感觉还是略慢点（特别是3长废话难受，必须手动） 5.F11暂停了好像还是有在移动鼠标 6.如关闭议题中，部分战斗卡墙情况（应该是训练问题，这不是问题） 7.在启动和F10恢复时，建议添加一个自动游戏前置的功能（老是忘）
> 
> 总结：目前无法实现全自动化我认为主要是1是不能优先获得其他代理人（当然低等级的也够了），2是战斗不能闪避，造成失败
> 
> 以下为DLC1内容： 1.我等了半天，然后才发现启动后自动暂停，并且无法F10恢复，因为代码里： `if __name__ == "__main__": task.pause() ` 2.由于对比main.py，缺失path环境变量部分，造成错误，无法继续 3.在对话交付部分，似乎是由于分辨率问题，无法正确点到对话项，但是其他按钮部分均正常 在money.py中，似乎这个是固定坐标，未做不同坐标识别，是否可以改为直接OCR识别？ `control.click(1020, 440)`

DLC补充一点，不同电脑的性能是脚本有一定影响，所以dlc不准备开放，很难做到所有电脑都能稳定运行，需要的自己调下参数自己用，相关功能已经很完善了
