### ISSUE TITLE
这个脚本，所有角色只会普攻是么。

### ISSUE THREAD

**Issue by pyf1835** [sMythicalBird/ZenlessZoneZero-Auto#62]
拿朱鸢，或者格莉丝打。因为是远程么？打的非常吃力。总挨揍。。。只会普工。自动闪避还都闪不掉

**Comment by sMythicalBird** [comment]
1.0没战斗设计，不过不是只有普工，还会放e。2.0那边加了战斗diy，你可以自己设计一套战斗逻辑
