### ISSUE TITLE
休闲点事件建议

### ISSUE THREAD

**Issue by hyj8247878** [sMythicalBird/ZenlessZoneZero-Auto#65]
![GC5@2JUF3844UJ3`PZY4MQP](https://github.com/user-attachments/assets/a403996f-fbc5-450e-8c47-8e2fabbc8fc5)
如图，在旧都列车前线刷零号业绩，寻路会去到中间的休息点触发休息事件，同时如果角色好感度高的话这个事件基本会硬控1分钟，可否在后续版本优化避免触发这个休息点的事件呢？

**Comment by sMythicalBird** [comment]
分类太多模型训练也麻烦，后面看看情况吧
