### ISSUE TITLE
空洞走格子测试情况

### ISSUE THREAD

**Issue by Presikid** [sMythicalBird/ZenlessZoneZero-Auto#66]
测试环境：64G内存
13600KF
RTX3060
ZhiTai TaiPlus5000 1TB
测试发现，在刷银行或者业绩的时候，一个完整的流程约为4：30，其中走格子超过了战斗时间的2倍。
建议：
1.走格子间隔适当加快或增加配置文件选项填写间隔
2.”通用对话事件“可把鼠标放在对话框左侧快速连点，不用等到字一个一个出现完毕后再点

**Comment by sMythicalBird** [comment]
> 测试环境：64G内存
> 13600KF
> RTX3060
> ZhiTai TaiPlus5000 1TB
> 测试发现，在刷银行或者业绩的时候，一个完整的流程约为4：30，其中走格子超过了战斗时间的2倍。
> 建议：
> 1.走格子间隔适当加快或增加配置文件选项填写间隔
> 2.”通用对话事件“可把鼠标放在对话框左侧快速连点，不用等到字一个一个出现完毕后再点

第一点，走格子加快文字概率影响图片识别，无法确定是否能一直正常检测，另外走格子间隔和识别速度有关，识别完了才会走，现在没有间隔，你所说的间隔是主要是ocr识别慢
第二点，乱点试过，问题非常多，有大概率会在对话点击玩后未停止乱点导致点到地图其他位置乱走

**Comment by sMythicalBird** [comment]
> 测试环境：64G内存
> 13600KF
> RTX3060
> ZhiTai TaiPlus5000 1TB
> 测试发现，在刷银行或者业绩的时候，一个完整的流程约为4：30，其中走格子超过了战斗时间的2倍。
> 建议：
> 1.走格子间隔适当加快或增加配置文件选项填写间隔
> 2.”通用对话事件“可把鼠标放在对话框左侧快速连点，不用等到字一个一个出现完毕后再点

通用点击并非是一定要用的，但在数百个不同页面的情况下，这个写起来是最省事的，如果你愿意整所有页面整理一下减少程序识别并进行后期维护，可以与我联系

**Comment by Presikid** [comment]
原来是OCR的问题，那没事了，我最初以为是为了程序预留容错留的delay。
