### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by chenmg2020** [sMythicalBird/ZenlessZoneZero-Auto#68]
有2点改进建议。
1、点击设置一个延时区间范围，然后取其中随机数延时，让它更像手动打的，避免被检测。
2、零号空洞“全通关“模式建议把零号业绩和银行都加上，想把这两个也刷了的就不用重复跑图了，或者在加一些模式，多样化选择。

**Comment by sMythicalBird** [comment]
> 有2点改进建议。
> 1、点击设置一个延时区间范围，然后取其中随机数延时，让它更像手动打的，避免被检测。
> 2、零号空洞“全通关“模式建议把零号业绩和银行都加上，想把这两个也刷了的就不用重复跑图了，或者在加一些模式，多样化选择。

两个问题分别回你
第一，战斗模块后续封装出来给你们自己调，这些不用担心
第二，从用户角度来说加这些东西争议很大，很多人就想打高难又想拿其他东西，但是评分拿不到s，众口难调，只要有一个人遇到了就会觉得是脚本问题，这些争论我我去回复也很累，有需要的可以自己改源码逻辑，这些我都是抽离出来的，改起来也简单。从开发者的角度来说，加很多状态变量固然可以实现很多功能，但是也意味着耦合度越来越高，每次重构代码都要重新离一套逻辑，出bug也更难溯源，除非逻辑框架不动了，不然暂时还是分离开进行设计
