### ISSUE TITLE
个人使用时跑图遇到的bug

### ISSUE THREAD

**Issue by TonyYTT** [sMythicalBird/ZenlessZoneZero-Auto#69]
我个人使用时发现跑图很多时候会卡在这种地方，但是程序自带的战斗倒计时没有计时，导致没有强退一直卡着。
建议倒计时从进图开始计不要停止。
另外如果后续要优化跑图的话建议跑图可以采集离目标的那个灰色的距离作为辅助（甚至感觉完全依赖那个距离来判断行动方向是否正确都可以），谢谢。

![Uploading 问题截图.png…]()

**Comment by TonyYTT** [comment]
好像图片不太好上传一直在uploading，我的问题图片同步上传到qq群里，谢谢。

**Comment by sMythicalBird** [comment]
大概是因为一直开在转向的循环里了，我待会改一下，不过这种图肯定是直接退掉重开的，开局好判断，中间出现卡栏杆的情况不好处理的，zzz没有小地图无法确定具体情况，你说的识别距离实现起来也并不好做

**Comment by TonyYTT** [comment]
> 大概是因为一直开在转向的循环里了，我待会改一下，不过这种图肯定是直接退掉重开的，开局好判断，中间出现卡栏杆的情况不好处理的，zzz没有小地图无法确定具体情况，你说的识别距离实现起来也并不好做

谢谢，明白了，辛苦了
