### ISSUE TITLE
main.py运行时28行报错

### ISSUE THREAD

**Issue by EArenZ4** [sMythicalBird/ZenlessZoneZero-Auto#75]
main文件里28行运行报错
line 28, in <module>
    from pynput.keyboard import Key, Listener
ModuleNotFoundError: No module named 'pynput'

**Comment by lazydog28** [comment]
没安装依赖，请按照Readme中的教程安装依赖

[Conda环境配置说明](https://github.com/sMythicalBird/ZenlessZoneZero-Auto/wiki/Conda%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E)
