### ISSUE TITLE
疑似有个bug 身上没有debuff会卡检疫门

### ISSUE THREAD

**Issue by twdjlzl** [sMythicalBird/ZenlessZoneZero-Auto#77]
身上没有debuff的时候如果检疫门在必经之路上会退出检疫门然后在那里循环 目前遇到了一次忘记截屏了 再次遇到我截个屏

**Comment by cmyyx** [comment]
看看日志，应该是没有识别到检疫门，用的是通用点击事件，更改游戏内字体试试
https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues/63#issuecomment-2252558054

**Comment by twdjlzl** [comment]
是选择推荐方案吗？ 我原先用的全局细体 还是说全局粗体更好识别一些？

**Comment by cmyyx** [comment]
优先推荐方案，识别不了就把细体和粗体都试一下

**Comment by twdjlzl** [comment]
ok 我多试几次 遇到了我截图发出来

**Comment by sMythicalBird** [comment]
> 身上没有debuff的时候如果检疫门在必经之路上会退出检疫门然后在那里循环 目前遇到了一次忘记截屏了 再次遇到我截个屏
系统字体默认，屏幕缩放率100，readme不是写了吗那边ocr识别有点问题
