### ISSUE TITLE
运行脚本不会进行正常操作

### ISSUE THREAD

**Issue by frg666** [sMythicalBird/ZenlessZoneZero-Auto#8]
python版本：3.12.4
Windows 11 专业版 23H2
屏幕缩放从1.5至1.0均已尝试，都只会乱划，手动进入游戏后会出现如下错误
> 2024-07-15 02:37:53.256 | DEBUG    | utils.init:<module>:31 - 初始化utils模块中
> 2024-07-15 02:37:53.283 | INFO     | utils.init:<module>:97 - 游戏窗口宽度为1536，高度为864,缩放因子为1.25,实际 宽度为1920,实际高度为1080
> 2024-07-15 02:37:53.283 | INFO     | utils.init:<module>:100 - 宽度缩放比例为1.5,高度缩放比例为1.5
> 2024-07-15 02:37:53.284 | INFO     | utils.init:<module>:101 - 菜单栏高度为28,左上角偏移量为(0.0,14.5)
> 2024-07-15 02:37:53.285 | DEBUG    | utils.download:check_file:58 - 开始检查文件！
> 2024-07-15 02:37:53.999 | DEBUG    | utils.download:check_file:91 - 文件检查完成！
> 2024-07-15 02:37:54.519 | DEBUG    | utils.map.components:<module>:25 - 加载地图组件标签成功！
> 2024-07-15 02:37:54.519 | DEBUG    | utils.map.components:<module>:30 - 加载地图组件信息成功！
> 2024-07-15 02:37:54.635 | INFO     | utils.config:<module>:14 - 加载配置文件 C:\Users\las83\ZenlessZoneZero-Auto\config.yaml
> 2024-07-15 02:37:54.636 | DEBUG    | utils:<module>:41 - 初始化utils模块完成
> 2024-07-15 02:37:54.649 | DEBUG    | utils.ocr.ocr:__init__:46 - 初始化OCR
> 2024-07-15 02:38:05.200 | DEBUG    | utils.ocr.ocr:__init__:88 - 初始化OCR完成
> 2024-07-15 02:38:05.204 | DEBUG    | utils.task:decorator:283 - 添加页面：确定操作
> 2024-07-15 02:38:05.205 | DEBUG    | utils.task:decorator:283 - 添加页面：确认操作
> 2024-07-15 02:38:05.205 | DEBUG    | utils.task:decorator:283 - 添加页面：选择_鸣徽或邦布
> 2024-07-15 02:38:05.205 | DEBUG    | utils.task:decorator:283 - 添加页面：选择_不可触碰
> 2024-07-15 02:38:05.206 | DEBUG    | utils.task:decorator:283 - 添加页面：离开操作
> 2024-07-15 02:38:05.206 | DEBUG    | utils.task:decorator:283 - 添加页面：目标位置
> 2024-07-15 02:38:05.206 | DEBUG    | utils.task:decorator:283 - 添加页面：邦布商人
> 2024-07-15 02:38:05.207 | DEBUG    | utils.task:decorator:283 - 添加页面：调查协会支援站
> 2024-07-15 02:38:05.207 | DEBUG    | utils.task:decorator:283 - 添加页面：调查协会支援站_狡兔屋
> 2024-07-15 02:38:05.207 | DEBUG    | utils.task:decorator:283 - 添加页面：馅饼天降
> 2024-07-15 02:38:05.208 | DEBUG    | utils.task:decorator:283 - 添加页面：呼叫增援_不增援
> 2024-07-15 02:38:05.208 | DEBUG    | utils.task:decorator:283 - 添加页面：催化
> 2024-07-15 02:38:05.209 | DEBUG    | utils.task:decorator:283 - 添加页面：投机客
> 2024-07-15 02:38:05.209 | DEBUG    | utils.task:decorator:283 - 添加页面：投机客_帮助_回复生命
> 2024-07-15 02:38:05.210 | DEBUG    | utils.task:decorator:283 - 添加页面：投机客_帮助_清除压力
> 2024-07-15 02:38:05.210 | DEBUG    | utils.task:decorator:283 - 添加页面：坍塌的房屋
> 2024-07-15 02:38:05.210 | DEBUG    | utils.task:decorator:283 - 添加页面：精锐邦布助手
> 2024-07-15 02:38:05.211 | DEBUG    | utils.task:decorator:283 - 添加页面：战斗中
> 2024-07-15 02:38:05.212 | DEBUG    | utils.task:decorator:283 - 添加页面：打不过跑路
> 2024-07-15 02:38:05.222 | INFO     | utils.detect.current:<module>:24 - 使用 CPUExecutionProvider 运行当前位置识别模型
> 2024-07-15 02:38:05.353 | DEBUG    | handle.others:<module>:19 - 地图名称: 旧都列车, 地图等级: 外围
> 2024-07-15 02:38:05.353 | DEBUG    | utils.task:decorator:283 - 添加页面：地图层数_1
> 2024-07-15 02:38:05.354 | DEBUG    | utils.task:decorator:283 - 添加页面：地图层数_2
> 2024-07-15 02:38:05.354 | DEBUG    | utils.task:decorator:283 - 添加页面：选择角色
> 2024-07-15 02:38:05.354 | DEBUG    | utils.task:decorator:283 - 添加页面：选择副本
> 2024-07-15 02:38:05.355 | DEBUG    | utils.task:decorator:283 - 添加页面：选择副本等级
> 2024-07-15 02:38:05.355 | DEBUG    | utils.task:decorator:283 - 添加页面：退出
> 2024-07-15 02:38:05.355 | DEBUG    | utils.task:decorator:283 - 添加页面：结算界面
> 2024-07-15 02:38:35.220 | DEBUG    | utils.task:__call__:334 - 当前页面：选择副本
> 2024-07-15 02:38:39.823 | DEBUG    | utils.task:__call__:334 - 当前页面：选择副本
> 2024-07-15 02:38:44.507 | DEBUG    | utils.task:__call__:334 - 当前页面：选择副本等级
> 2024-07-15 02:38:51.299 | DEBUG    | utils.task:__call__:334 - 当前页面：选择角色
> 2024-07-15 02:39:09.801 | DEBUG    | utils.task:__call__:334 - 当前页面：地图层数_1
> Traceback (most recent call last):
>   File "C:\Users\las83\ZenlessZoneZero-Auto\main.py", line 27, in <module>
>     task.run()
>   File "C:\Users\las83\ZenlessZoneZero-Auto\utils\task.py", line 367, in run
>     self()  # 执行任务
>     ^^^^^^
>   File "C:\Users\las83\ZenlessZoneZero-Auto\utils\task.py", line 342, in __call__
>     page.action(**params)  # 执行页面操作函数
>     ^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\las83\ZenlessZoneZero-Auto\handle\others.py", line 49, in grid_map_1
>     (mc, dirct) = info.mapWay[info.step]
>                   ~~~~~~~~~~~^^^^^^^^^^^
> IndexError: list index out of range

**Comment by frg666** [comment]
好像是游戏分辨率问题，我再看看

**Comment by sMythicalBird** [comment]
重新运行一下试试，讲道理数组越界那边加过保护，应该不会出现，后面自动寻路会继续优化

**Comment by frg666** [comment]
> 重新运行一下试试，讲道理数组越界那边加过保护，应该不会出现，后面自动寻路会继续优化
就是游戏分辨率的问题，已经搞定
