### ISSUE TITLE
不同代理人碰撞箱不同与楼梯交互造成的bug

### ISSUE THREAD

**Issue by Presikid** [sMythicalBird/ZenlessZoneZero-Auto#80]
不同代理人碰撞箱不同与楼梯交互造成的bug：
代理人11号在列车·前线地图中，2天内累计3次复现此bug，如图所示，11号容易在楼梯脚下位置卡住
![1](https://github.com/user-attachments/assets/649e3050-253f-43cf-8020-6b1043ea741c)
补充：此处的卡住指程序检测不到代理人被卡住，一直向前走，但是走不过去
_Originally posted by @Presikid in https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues/63#issuecomment-2257213485_
今天早上想起来bug直接塞2.0bug汇总里去了，没想到2.1已经发了，那就拎到外面发一下

**Comment by sMythicalBird** [comment]
> 不同代理人碰撞箱不同与楼梯交互造成的bug：
> 代理人11号在列车·前线地图中，2天内累计3次复现此bug，如图所示，11号容易在楼梯脚下位置卡住
> ![1](https://github.com/user-attachments/assets/649e3050-253f-43cf-8020-6b1043ea741c)
> 补充：此处的卡住指程序检测不到代理人被卡住，一直向前走，但是走不过去
> _Originally posted by @Presikid in https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues/63#issuecomment-2257213485_
> 今天早上想起来bug直接塞2.0bug汇总里去了，没想到2.1已经发了，那就拎到外面发一下
>             

这个到时间自己退就行了，这张图不好做适配，zzz没有小地图，现在的战斗寻路只能解决障碍物少的地形
