### ISSUE TITLE
更新新的战斗策略后，小概率战斗结束进入棋盘仍在执行默认战斗策略

### ISSUE THREAD

**Issue by xlone2001** [sMythicalBird/ZenlessZoneZero-Auto#81]
更新最新2.1版本代码，包含战斗策略更新。
战斗结束画面中的黄色画面会激活“黄光”战斗策略，然后转“默认”战斗策略。
如果战斗结束动画加载的比较快，概率进入棋盘地图后仍然在执行默认战斗，而不是退出战斗执行状态。
结果就是在棋盘格子一直执行w键向上而卡住，直至超时。
由于战斗策略中都有延时操作，是否会在退出战斗状态后重新触发战斗相关脚本？
是否可以在识别到棋盘格后清理下战斗状态标志，多次清理来避免战斗指令一直不退出？
该问题今天已经遇到3次。

另外自动寻路在我电脑上遇到问题，设置已恢复为默认，寻路时自动向左调整一下视角就过于偏左，然后自动向右调整视角又偏右，不知道是不是拉视角的距离或时间偏大。自己手动将输入里的镜头灵敏度（x轴）下调1个等级后正常，供参考。

**Comment by sMythicalBird** [comment]
退出动画里会识别到黄光，但是之后退出战斗逻辑不应该出现你这种情况，我测试也没有遇到，你说的w向前，应该是初次进入战斗的情况，但从逻辑上来说上一次战斗退出之后，还会识别黄光，之后在退出战斗，然而这是已经没有战斗的特征了，不会再次进入战斗，你可以录个你出问题的视频私发我一下，cmd要录在里面，我看看具体情况

**Comment by Victor2333** [comment]
我也碰到相同的问题了 退出战斗后 走格子画面 不停触发按 “w” 发生了一次 没记录日志 下次再出现记录下

另外 自动寻路的问题我也碰到了 小概率会卡顶着墙卡死

**Comment by sMythicalBird** [comment]
执行几组战斗逻辑会切出来做一次寻路的，你应该等一会看看会不会继续寻路，顶着墙卡死的那种一般是原点在正前方，那个目前只能等时间到了自动退出。
关于退出之后还按w的目前我没找到原因，逻辑上应该不成立，这个还挺奇怪的，等后面遇到再看看

**Comment by Victor2333** [comment]
@sMythicalBird 我碰到的就是这种
https://github.com/sMythicalBird/ZenlessZoneZero-Auto/issues/63#issuecomment-2258349341
