### ISSUE TITLE
2.1版本特殊区域7777无限重复进入指令

### ISSUE THREAD

**Issue by Korlne** [sMythicalBird/ZenlessZoneZero-Auto#82]
进入特殊区域的娱乐区后程序会重复“进入特殊区域”的指令，无法推进进度
测试于 旧都列车·内部 
![Z0(_BUZ09JQR}P_8G2(5FYV](https://github.com/user-attachments/assets/29d3b381-b956-4b9f-a3df-0c05cebf884c)
![(%E2~Y9FJ{P$}_WA2B1S8S1](https://github.com/user-attachments/assets/38cd7d36-05e4-4d7d-9407-956bdc62a024)

**Comment by sMythicalBird** [comment]
这张图不能离开吗

**Comment by Korlne** [comment]
> 这张图不能离开吗

好问题，从来没试过能不能离开。不过程序确实在这里无限重复了，一直没有动作

**Comment by sMythicalBird** [comment]
等遇到看看能不能离开，一般默认直接离开，如果一直重复那可能要拉四次了
