### ISSUE TITLE
旧都列车腹地

### ISSUE THREAD

**Issue by noobcomanro** [sMythicalBird/ZenlessZoneZero-Auto#83]
第一层有时候识别不到地图，然后一直两三个格子来回跳
选刷业绩的模式，第一次在第一层拿到业绩后退出了不知道是否正常。第二次直接跳过所有业绩一直向下层打，最后一层不知道什么原因一直向上走没路了就一直撞墙

**Comment by pansx** [comment]
试了一下确实有这个问题,第二次虽然镜头一直在拉上右上角却一直在向左边走最后银行存钱退出,第三次直接打通关,后面都是随机在存钱和打通关之间随机,再没有去拿业绩了

**Comment by Victor2333** [comment]
我也碰到相同的问题了 走格子画面 不停触发按 “w” 发生了一次 没记录日志 下次再出现记录下

**Comment by sMythicalBird** [comment]
你们选的什么模式

**Comment by noobcomanro** [comment]
> 你们选的什么模式

单刷业绩的模式，只有第一次的第一层能拿到业绩。后面就直接进下一层了

**Comment by noobcomanro** [comment]
选零号业绩这个模式的时候第一次在第一层拿到业绩就会退出结束。再重复的时候，视角会向右拖动但是不拿业绩人物把外面的事件触发：右边那个三选一的事件不触发，后进入下一层，第三层也是这样

**Comment by noobcomanro** [comment]
> > > 你们选的什么模式
> > 
> > 
> > 单刷业绩的模式，只有第一次的第一层能拿到业绩。后面就直接进下一层了
> 
> 你是拿到业绩之后又去了下一层，那这时候地图还会被拖动吗，往哪拖的

选零号业绩这个模式的时候第一次在第一层拿到业绩就会退出结束。再重复的时候，视角会向右拖动但是不拿业绩人物把外面的事件触发：右边那个三选一的事件不触发，后进入下一层，第三层也是这样

**Comment by pansx** [comment]
刷业绩模式,循环1非常正常第二层能成功拿到业绩并退出,循环2自动进图打到第二层虽然还是向右上角业绩的格子拉镜头,但是会一直向左边走去银行存3次退出,第三次到第二层依然会拉向业绩格子,但直线向上走后进入了传送点,会直接打完整个空洞不理会业绩格,之后挂了一段时间都是在去银行和通关这两个里面随机,再也没去拿过业绩

**Comment by sMythicalBird** [comment]
找到原因了，之前加模式4的时候业绩那边漏了个判断，刚改完，我测下没问题在更新，你们晚点拉一下新的
