### ISSUE TITLE
F11 快捷键

### ISSUE THREAD

**Issue by lifeek23** [sMythicalBird/ZenlessZoneZero-Auto#85]
想问一下F11快捷键会使cmd窗口全屏或退出全屏，而且好像没有找到禁止的办法，这个问题是普遍存在的吗

**Comment by lazydog28** [comment]
F11快捷键不需要非得在cmd窗口按下，可以在桌面或者游戏窗口按下即可

**Comment by lifeek23** [comment]
哦哦，明白了，谢谢
