### ISSUE TITLE
选择的刷业绩，但是会傻愣愣的去第三层，经常发生

### ISSUE THREAD

**Issue by Anjou99** [sMythicalBird/ZenlessZoneZero-Auto#86]
![PixPin_2024-07-30_21-57-44](https://github.com/user-attachments/assets/7899ca40-2dd9-485e-aaa1-5458766489a1)
![PixPin_2024-07-30_22-01-56](https://github.com/user-attachments/assets/2fe6b70a-bd50-435f-aa67-17f4ce108081)

选择的刷业绩，但是会傻愣愣的去第三层，经常发生

**Comment by sMythicalBird** [comment]
配置文件把标题截出来，我看看是哪个

**Comment by sMythicalBird** [comment]
找到了，之前加模式4的时候漏了个判断，刚修完，等会测试没问题merge，你晚点拉一下新代码
