### ISSUE TITLE
零号银行模式[2,1,3]路线改进的建议

### ISSUE THREAD

**Issue by Presikid** [sMythicalBird/ZenlessZoneZero-Auto#89]
对于零号银行存钱路线的改进
一般来说刷零号银行存钱都是在列车前线地图刷，一刷就是很多把，所以单个循环能减少一定时间都是大幅优化，这边建议把路线改一下，如图所示
![微信图片_20240731094629](https://github.com/user-attachments/assets/f6989d59-55e4-423e-a7f2-a855499d89c9)
这样走的好处是不去碰哪个医药协会还是什么东西，减少非常多的对话，单个轮回可以少很多时间，而且经过两天爆刷的测试，列车前线第二层这里的休息处，蓝色线路不会刷奇怪的东西，所以推荐这么改一下，大幅优化效率

**Comment by sMythicalBird** [comment]
> 对于零号银行存钱路线的改进
> 一般来说刷零号银行存钱都是在列车前线地图刷，一刷就是很多把，所以单个循环能减少一定时间都是大幅优化，这边建议把路线改一下，如图所示
> ![微信图片_20240731094629](https://github.com/user-attachments/assets/f6989d59-55e4-423e-a7f2-a855499d89c9)
> 这样走的好处是不去碰哪个医药协会还是什么东西，减少非常多的对话，单个轮回可以少很多时间，而且经过两天爆刷的测试，列车前线第二层这里的休息处，蓝色线路不会刷奇怪的东西，所以推荐这么改一下，大幅优化效率

这个问题昨天就改了，换新代码
