### ISSUE TITLE
截取屏幕失败报错

### ISSUE THREAD

**Issue by ShangguanHong** [sMythicalBird/ZenlessZoneZero-Auto#91]
![Snipaste_2024-07-31_10-55-37](https://github.com/user-attachments/assets/30157732-2e03-4cbc-897e-97da9046e9ed)
![Snipaste_2024-07-31_10-55-53](https://github.com/user-attachments/assets/5334df7f-3b3e-4b30-bc2d-4b37abd38077)

**Comment by sMythicalBird** [comment]
游戏放前台

**Comment by ShangguanHong** [comment]
我游戏是放前台的，前面是正常运行，然后运行一段时间之后就会报这个错误

**Comment by lazydog28** [comment]
脚本运行时是否有修改系统缩放比例或者其他操作？

**Comment by ShangguanHong** [comment]
运行过程中未修改系统缩放比例或者其他操作，但是有按f11暂停后修改系统缩放比例过，可能是因为这个问题导致的吗？

**Comment by lazydog28** [comment]
> 运行过程中未修改系统缩放比例或者其他操作，但是有按f11暂停后修改系统缩放比例过，可能是因为这个问题导致的吗？

嗯
