### ISSUE TITLE
conda 无法解决install  - cudnn==8.9.7.29 

### ISSUE THREAD

**Issue by SkyleYu** [sMythicalBird/ZenlessZoneZero-Auto#92]
conda PackagesNotFoundError: The following packages are not available from current channels:    - cudnn==8.9.7.29
现有解决方式是添加一个forge： conda config --add channels conda-forge

**Comment by lazydog28** [comment]
> conda PackagesNotFoundError: The following packages are not available from current channels: - cudnn==8.9.7.29 现有解决方式是添加一个forge： conda config --add channels conda-forge

`conda install cudnn=8.9.7.29`
