### ISSUE TITLE
最短路线有反向传送带会不断重复向下 

### ISSUE THREAD

**Issue by twdjlzl** [sMythicalBird/ZenlessZoneZero-Auto#94]
最短路线有反向传送带会不断重复向下 录了个视频附上截图在下面

https://drive.google.com/file/d/1uH-caGuXVpradhCNzO-9gsQNfdFQAXEj/view?usp=sharing

![屏幕截图 2024-07-31 233707](https://github.com/user-attachments/assets/ab61c737-5626-41ab-97a9-85558daeff52)

**Comment by twdjlzl** [comment]
尝试压缩但是压缩完就代码就看不清了
https://drive.google.com/file/d/1ZJNPSxzoGnSiZY-eO8GHDJlj4PYLweU5/view?usp=sharing

**Comment by lazydog28** [comment]
当前版本未对传送带进行识别，请先刷不包含传送的地图，等以后模型更新再刷
