### ISSUE TITLE
打关底关时进不去

### ISSUE THREAD

**Issue by seywea** [sMythicalBird/ZenlessZoneZero-Auto#95]
走完一层后最后一关会踩上去后又去摸相邻的鸣徽，然后在返回后不会按F键再次触发事件导致一直卡住反复进出关底关，打的旧都列车前线，分辨率1280＊720，棋盘速度也改成1了。💦

**Comment by lazydog28** [comment]
截图

**Comment by sMythicalBird** [comment]
看下屏幕缩放是不是100%，部分设备的ocr识别效果不好，这种情况一般是ocr没识别到退出了，再次进入终点就进不去了
