### ISSUE TITLE
懒人启动器的源码可否开源以便协助修复bug

### ISSUE THREAD

**Issue by AdiEcho** [sMythicalBird/ZenlessZoneZero-Auto#98]
有意协助开发修复bug，在群里见到有懒人启动器的bug但是没有源码无法修复构建一个新的exe出来

**Comment by lazydog28** [comment]
具体是什么BUG？

**Comment by AdiEcho** [comment]
> 具体是什么BUG？

1. 无法通过懒人启动器安装cpu启动的依赖
2. 安装依赖指定版本依赖没有明确使用方法，暂时不清楚这是不是一个bug。输入2后回车会报错unexpected newline，用户无法手动输入需要安装的包
![image](https://github.com/user-attachments/assets/55baf022-c669-4b57-93e5-b5dafcac10e2)
需要输入 2+空格+需要安装的包 才能使用
![image](https://github.com/user-attachments/assets/80163b85-d9ca-4f3b-9b98-7d26af65a2e9)
我个人偏向该功能出现bug了，因为看到有一行 请输入需要安装的包名:

**Comment by lazydog28** [comment]
安装依赖版本取决于系统内是否存在nvidia显卡，如果拥有nvida显卡则安装GPU版本依赖否则安装CPU依赖。如果GPU版本运行有问题，可以在配置文件禁用GPU。

第二个问题确实存在，马上进行修复

**Comment by AdiEcho** [comment]
cpu和gpu的依赖还是有区别的吧，群里是有一个安装了gpu版本但是用cpu执行失败的，建议还是留一个CPU的安装选项
![e087c21a3abb7efcb6c6e86d1ac40b92](https://github.com/user-attachments/assets/12283fed-41d4-4b45-8a87-84841534b960)

**Comment by lazydog28** [comment]
好的

**Comment by lazydog28** [comment]
已经更新
